"""
import_maec.py — Full conversion of Import_maec/Program.cs (C# .NET)
Jerome Athias - XORCISM

Imports the values of MITRE MAEC's default vocabularies (XSD file
"maec_default_vocabularies.xsd") into XORCISM.db (+ XMALWARE.db for the
Malware* enumerations).

Principle (identical to the C#): the XSD contains <xs:simpleType> named
"<Enumeration>Enum-<version>"; each restriction lists <xs:enumeration
value="…"> with an <xs:annotation><xs:documentation>…</xs:documentation>.
For each simpleType:
  1. VERSION (VersionValue=<version>)            — XORCISM
  2. ENUMERATIONVERSION (EnumerationName, VersionID) — XORCISM
  3. one row per value in the table dedicated to the enumeration
     (column <…>Name = value, <…>Description = documentation,
      EnumerationVersionID, VocabularyID, CreatedDate).

The very long "if/else" of the C# (87 enumerations) is replaced by an
ENUM_MAP mapping table: enum → (table, Name column, database). The Description
column is derived ("…Name" → "…Description") and validated against the model
(fixing 4 typos from the original C# along the way).

Usage:
    python import_maec.py --xsd maec_default_vocabularies.xsd
    python import_maec.py --download
"""

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Optional

import requests
from sqlalchemy import event, text, Integer, BigInteger, SmallInteger
from sqlalchemy.orm import Mapper

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
from xorcism_python.models.base import session_scope
from xorcism_python.models import xorcism as M_XORCISM
from xorcism_python.models import xmalware as M_XMALWARE
from xorcism_python.utils import log

MODULE = "ImportMAEC"
MAEC_VERSION = "4.1"  # MAEC vocabulary version (HARDCODED in the C#)
# MAEC schema archived on GitHub (may move — provide the local file if needed).
MAEC_URL = (
    "https://raw.githubusercontent.com/MAECProject/schemas/master/"
    "maec_default_vocabularies.xsd"
)

XSD_NS = "http://www.w3.org/2001/XMLSchema"


# ─── Auto-increment of integer primary keys (cf. other importers) ───────

_pk_counters: dict = {}
_INT_TYPES = (Integer, BigInteger, SmallInteger)


def _auto_pk(mapper, connection, target) -> None:
    pk_cols = mapper.primary_key
    if len(pk_cols) != 1:
        return
    col = pk_cols[0]
    if not isinstance(col.type, _INT_TYPES):
        return
    attr = mapper.get_property_by_column(col).key
    if getattr(target, attr, None) is not None:
        return
    tbl = mapper.local_table.name
    key = (str(connection.engine.url), tbl)
    db_max = connection.execute(
        text(f'SELECT COALESCE(MAX("{col.name}"), 0) FROM "{tbl}"')
    ).scalar()
    nxt = max(_pk_counters.get(key, 0), int(db_max or 0)) + 1
    _pk_counters[key] = nxt
    setattr(target, attr, nxt)


event.listen(Mapper, "before_insert", _auto_pk)


# ─── Mapping table enum → (table, Name column, database) ──────────────
# Generated by extraction from Import_maec/Program.cs (87 enumerations).
ENUM_MAP = [
    ("ActionObjectAssociationTypeEnum", "ACTIONOBJECTASSOCIATIONTYPE", "ActionObjectAssociationTypeName", "XORCISM"),
    ("AntiBehavioralAnalysisPropertiesEnum", "ANTIBEHAVIORANALYSISPROPERTIES", "AntiBehavioralAnalysisPropertiesName", "XORCISM"),
    ("AntiBehavioralAnalysisStrategicObjectivesEnum", "ANTIBEHAVIORALANALYSISSTRATEGICOBJECTIVE", "AntiBehavioralAnalysisStrategicObjectiveName", "XORCISM"),
    ("AntiBehavioralAnalysisTacticalObjectivesEnum", "ANTIBEHAVIORALANALYSISTACTICALOBJECTIVE", "AntiBehavioralAnalysisTacticalObjectiveName", "XORCISM"),
    ("AntiCodeAnalysisStrategicObjectivesEnum", "ANTICODEANALYSISSTRATEGICOBJECTIVE", "AntiCodeAnalysisStrategicObjectiveName", "XORCISM"),
    ("AntiCodeAnalysisTacticalObjectivesEnum", "ANTICODEANALYSISTACTICALOBJECTIVE", "AntiCodeAnalysisTacticalObjectiveName", "XORCISM"),
    ("AntiDetectionStrategicObjectivesEnum", "ANTIDETECTIONSTRATEGICOBJECTIVE", "AntiDetectionStrategicObjectiveName", "XORCISM"),
    ("AntiDetectionTacticalObjectivesEnum", "ANTIDETECTIONTACTICALOBJECTIVE", "AntiDetectionTacticalObjectiveName", "XORCISM"),
    ("AntiRemovalStrategicObjectivesEnum", "ANTIREMOVALSTRATEGICOBJECTIVE", "AntiRemovalStrategicObjectiveName", "XORCISM"),
    ("AntiRemovalTacticalObjectivesEnum", "ANTIREMOVALTACTICALOBJECTIVE", "AntiRemovalTacticalObjectiveName", "XORCISM"),
    ("AvailabilityViolationPropertiesEnum", "AVAILABILITYVIOLATIONPROPERTIES", "AvailabilityViolationPropertiesName", "XORCISM"),
    ("AvailabilityViolationStrategicObjectivesEnum", "AVAILABILITYVIOLATIONSTRATEGICOBJECTIVE", "AvailabilityViolationStrategicObjectiveName", "XORCISM"),
    ("AvailabilityViolationTacticalObjectivesEnum", "AVAILABILITYVIOLATIONTACTICALOBJECTIVE", "AvailabilityViolationTacticalObjectiveName", "XORCISM"),
    ("CapabilityObjectiveRelationshipEnum", "CAPABILITYOBJECTIVERELATIONSHIP", "CapabilityObjectiveRelashionshipName", "XORCISM"),
    ("CommandandControlPropertiesEnum", "COMMANDANDCONTROLPROPERTIES", "CommandandControlPropertiesName", "XORCISM"),
    ("CommandandControlStrategicObjectivesEnum", "COMMANDANDCONTROLSTRATEGICOBJECTIVE", "CommandandControlStrategicObjectiveName", "XORCISM"),
    ("CommandandControlTacticalObjectivesEnum", "COMMANDANDCONTROLTACTICALOBJECTIVE", "CommandandControlTacticalObjectiveName", "XORCISM"),
    ("CommonCapabilityPropertiesEnum", "COMMONCAPABILITYPROPERTIES", "CommonCapabilityPropertiesName", "XORCISM"),
    ("DataExfiltrationPropertiesEnum", "DATAEXFILTRATIONPROPERTIES", "DataExfiltrationPropertiesName", "XORCISM"),
    ("DataExfiltrationStrategicObjectivesEnum", "DATAEXFILTRATIONSTRATEGICOBJECTIVE", "DataExfiltrationStrategicObjectiveName", "XORCISM"),
    ("DataExfiltrationTacticalObjectivesEnum", "DATAEXFILTRATIONTACTICALOBJECTIVE", "DataExfiltrationTacticalObjectiveName", "XORCISM"),
    ("DataTheftPropertiesEnum", "DATATHEFTPROPERTIES", "DataTheftPropertiesName", "XORCISM"),
    ("DataTheftStrategicObjectivesEnum", "DATATHEFTSTRATEGICOBJECTIVE", "DataTheftStrategicObjectiveName", "XORCISM"),
    ("DataTheftTacticalObjectivesEnum", "DATATHEFTTACTICALOBJECTIVE", "DataTheftTacticalObjectiveName", "XORCISM"),
    ("DebuggingActionNameEnum", "DEBUGGINGACTIONNAME", "DebuggingActionNameName", "XORCISM"),
    ("DestructionPropertiesEnum", "DESTRUCTIONPROPERTIES", "DestructionPropertiesName", "XORCISM"),
    ("DestructionStrategicObjectivesEnum", "DESTRUCTIONSTRATEGICOBJECTIVE", "DestructionStrategicObjectiveName", "XORCISM"),
    ("DestructionTacticalObjectivesEnum", "DESTRUCTIONTACTICALOBJECTIVE", "DestructionTacticalObjectiveName", "XORCISM"),
    ("DeviceDriverActionNameEnum", "DEVICEDRIVERACTIONNAME", "DeviceDriverActionNameName", "XORCISM"),
    ("DirectoryActionNameEnum", "DIRECTORYACTIONNAME", "DirectoryActionNameName", "XORCISM"),
    ("DiskActionNameEnum", "DISKACTIONNAME", "DiskActionNameName", "XORCISM"),
    ("DNSActionNameEnum", "DNSACTIONNAME", "DNSActionNameName", "XORCISM"),
    ("FileActionNameEnum", "FILEACTIONNAME", "FileActionNameName", "XORCISM"),
    ("FraudStrategicObjectivesEnum", "FRAUDSTRATEGICOBJECTIVE", "FraudStrategicObjectiveName", "XORCISM"),
    ("FraudTacticalObjectivesEnum", "FRAUDTACTICALOBJECTIVE", "FraudTacticalObjectiveName", "XORCISM"),
    ("FTPActionNameEnum", "FTPACTIONNAME", "FTPActionNameName", "XORCISM"),
    ("GroupingRelationshipEnum", "GROUPINGRELATIONSHIP", "GroupingRelationshipName", "XORCISM"),
    ("GUIActionNameEnum", "GUIACTIONNAME", "GUIActionNameName", "XORCISM"),
    ("HookingActionNameEnum", "HOOKINGACTIONNAME", "HookingActionNameName", "XORCISM"),
    ("HTTPActionNameEnum", "HTTPACTIONNAME", "HTTPActionNameName", "XORCISM"),
    ("ImportanceTypeEnum", "IMPORTANCETYPE", "ImportanceTypeName", "XORCISM"),
    ("InfectionPropagationPropertiesEnum", "INFECTIONPROPAGATIONPROPERTIES", "InfectionPropagationPropertiesName", "XORCISM"),
    ("InfectionPropagationStrategicObjectivesEnum", "INFECTIONPROPAGATIONSTRATEGICOBJECTIVE", "InfectionPropagationStrategicObjectiveName", "XORCISM"),
    ("InfectionPropagationTacticalObjectivesEnum", "INFECTIONPROPAGATIONTACTICALOBJECTIVE", "InfectionPropagationTacticalObjectiveName", "XORCISM"),
    ("IntegrityViolationStrategicObjectivesEnum", "INTEGRITYVIOLATIONSTRATEGICOBJECTIVE", "IntegrityViolationStrategicObjectiveName", "XORCISM"),
    ("IntegrityViolationTacticalObjectivesEnum", "INTEGRITYVIOLATIONTACTICALOBJECTIVE", "IntegrityViolationTacticalObjectiveName", "XORCISM"),
    ("IPCActionNameEnum", "IPCACTIONNAME", "IPCActionNameName", "XORCISM"),
    ("IRCActionNameEnum", "IRCACTIONNAME", "IRCActionNameName", "XORCISM"),
    ("LibraryActionNameEnum", "LIBRARYACTIONNAME", "LibraryActionNameName", "XORCISM"),
    ("MachineAccessControlPropertiesEnum", "MACHINEACCESSCONTROLPROPERTIES", "MachineAccessControlPropertiesName", "XORCISM"),
    ("MachineAccessControlStrategicObjectivesEnum", "MACHINEACCESSCONTROLSTRATEGICOBJECTIVE", "MachineAccessControlStrategicObjectiveName", "XORCISM"),
    ("MachineAccessControlTacticalObjectivesEnum", "MACHINEACCESSCONTROLTACTICALOBJECTIVE", "MachineAccessControlTacticalObjectiveName", "XORCISM"),
    ("MalwareCapabilityEnum", "MALWARECAPABILITY", "MalwareCapabilityName", "XMALWARE"),
    ("MalwareConfigurationParameterEnum", "MALWARECONFIGURATIONPARAMETER", "MalwareConfigurationParameterName", "XMALWARE"),
    ("MalwareDevelopmentToolEnum", "MALWAREDEVTOOL", "MalwareDevelopmentToolName", "XMALWARE"),
    ("MalwareEntityTypeEnum", "MALWAREENTITY", "MalwareEntityName", "XMALWARE"),
    ("MalwareLabelEnum", "MALWARELABEL", "MalwareLabelName", "XMALWARE"),
    ("MalwareSubjectRelationshipEnum", "MALWARESUBJECTRELATIONSHIP", "MalwareSubjectRelationshipName", "XMALWARE"),
    ("NetworkActionNameEnum", "NETWORKACTIONNAME", "NetworkActionNameName", "XORCISM"),
    ("NetworkShareActionNameEnum", "NETWORKSHAREACTIONNAME", "NetworkShareActionNameName", "XORCISM"),
    ("PersistencePropertiesEnum", "PERSISTENCEPROPERTIES", "PersistencePropertiesName", "XORCISM"),
    ("PersistenceStrategicObjectivesEnum", "PERSISTENCESTRATEGICOBJECTIVE", "PersistenceStrategicObjectiveName", "XORCISM"),
    ("PersistenceTacticalObjectivesEnum", "PERSISTENCETACTICALOBJECTIVE", "PersistenceTacticalObjectiveName", "XORCISM"),
    ("PrivilegeEscalationPropertiesEnum", "PRIVILEGEESCALATIONPROPERTIES", "PrivilegeEscalationPropertiesName", "XORCISM"),
    ("PrivilegeEscalationStrategicObjectivesEnum", "PRIVILEGEESCALATIONSTRATEGICOBJECTIVE", "PrivilegeEscalationStrategicObjectiveName", "XORCISM"),
    ("PrivilegeEscalationTacticalObjectivesEnum", "PRIVILEGEESCALATIONTACTICALOBJECTIVE", "PrivilegeEscalationTacticalObjectiveName", "XORCISM"),
    ("ProbingStrategicObjectivesEnum", "PROBINGSTRATEGICOBJECTIVE", "ProbingStrategicObjectiveName", "XORCISM"),
    ("ProbingTacticalObjectivesEnum", "PROBINGTACTICALOBJECTIVE", "ProbingTacticalObjectiveName", "XORCISM"),
    ("ProcessMemoryActionNameEnum", "PROCESSMEMORYACTIONNAME", "ProcessMemoryActionNameName", "XORCISM"),
    ("ProcessActionNameEnum", "PROCESSACTIONNAME", "ProcessActionNameName", "XORCISM"),
    ("ProcessThreadActionNameEnum", "PROCESSTHREADACTIONNAME", "ProcessThreadActionNameName", "XORCISM"),
    ("RegistryActionNameEnum", "REGISTRYACTIONNAME", "RegistryActionNameName", "XORCISM"),
    ("RemoteMachineManipulationStrategicObjectivesEnum", "REMOTEMACHINEMANIPULATIONSTRATEGICOBJECTIVE", "RemoteMachineManipulationStrategicObjectiveName", "XORCISM"),
    ("RemoteMachineManipulationTacticalObjectivesEnum", "REMOTEMACHINEMANIPULATIONTACTICALOBJECTIVE", "RemoteMachineManipulationTacticalObjectiveName", "XORCISM"),
    ("SecondaryOperationPropertiesEnum", "SECONDARYOPERATIONPROPERTIES", "SecondaryOperationPropertiesName", "XORCISM"),
    ("SecondaryOperationStrategicObjectivesEnum", "SECONDARYOPERATIONSTRATEGICOBJECTIVE", "SecondaryOperationStrategicObjectiveName", "XORCISM"),
    ("SecondaryOperationTacticalObjectivesEnum", "SECONDARYOPERATIONTACTICALOBJECTIVE", "SecondaryOperationTacticalObjectiveName", "XORCISM"),
    ("SecurityDegradationPropertiesEnum", "SECURITYDEGRADATIONPROPERTIES", "SecurityDegradationPropertiesName", "XORCISM"),
    ("SecurityDegradationStrategicObjectivesEnum", "SECURITYDEGRADATIONSTRATEGICOBJECTIVE", "SecurityDegradationStrategicObjectiveName", "XORCISM"),
    ("SecurityDegradationTacticalObjectivesEnum", "SECURITYDEGRADATIONTACTICALOBJECTIVE", "SecurityDegradationTacticalObjectiveName", "XORCISM"),
    ("ServiceActionNameEnum", "SERVICEACTIONNAME", "ServiceActionNameName", "XORCISM"),
    ("SocketActionNameEnum", "SOCKETACTIONNAME", "SocketActionNameName", "XORCISM"),
    ("SpyingStrategicObjectivesEnum", "SPYINGSTRATEGICOBJECTIVE", "SpyingStrategicObjectiveName", "XORCISM"),
    ("SpyingTacticalObjectivesEnum", "SPYINGTACTICALOBJECTIVE", "SpyingTacticalObjectiveName", "XORCISM"),
    ("SynchronizationActionNameEnum", "SYNCHRONIZATIONACTIONNAME", "SynchronizationActionNameName", "XORCISM"),
    ("SystemActionNameEnum", "SYSTEMACTIONNAME", "SystemActionNameName", "XORCISM"),
    ("UserActionNameEnum", "USERACTIONNAME", "UserActionNameName", "XORCISM"),
]

# Index : enum name → (table, name_col, bind)
ENUM_BY_NAME = {row[0]: row[1:] for row in ENUM_MAP}


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1] if "}" in tag else tag


def _text(el: Optional[ET.Element]) -> str:
    if el is None:
        return ""
    return "".join(el.itertext()).strip()


def _clean(s: str) -> str:
    if not s:
        return ""
    s = s.replace("\r\n", " ").replace("\n", " ").replace("\t", " ")
    while "  " in s:
        s = s.replace("  ", " ")
    return s.strip()


def _trunc(s: Optional[str], n: int) -> Optional[str]:
    if not s:
        return None
    return s[:n]


def _now() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


def _model_for(table: str, bind: str):
    mod = M_XMALWARE if bind == "XMALWARE" else M_XORCISM
    return getattr(mod, table)


def _cols(model) -> set:
    return {c.name for c in model.__table__.columns}


def _desc_col(name_col: str) -> str:
    """"…Name" → "…Description"."""
    base = name_col[:-4] if name_col.endswith("Name") else name_col
    return base + "Description"


def _resolve_desc_col(model, name_col: str) -> Optional[str]:
    """Real "description" column of the model (handles 2 typo'd
    "…Destruction" columns present in the original schema). None if absent."""
    cols = _cols(model)
    base = name_col[:-4] if name_col.endswith("Name") else name_col
    for cand in (base + "Description", base + "Destruction"):
        if cand in cols:
            return cand
    # Last resort: any column resembling a description
    for c in cols:
        if c != name_col and (c.endswith("Description") or c.endswith("Destruction")):
            return c
    return None


# ─── Download ────────────────────────────────────────────────────────────────

def download_maec(dest: str) -> None:
    log(MODULE, f"Téléchargement de {MAEC_URL}")
    resp = requests.get(MAEC_URL, timeout=180)
    resp.raise_for_status()
    with open(dest, "wb") as f:
        f.write(resp.content)
    log(MODULE, f"Fichier sauvegardé : {dest}")


# ─── VOCABULARY / VERSION / ENUMERATIONVERSION ───────────────────────────────

def _setup_vocabulary(xorcism_session) -> int:
    from xorcism_python.models.xorcism import VOCABULARY
    vocab = xorcism_session.query(VOCABULARY).filter_by(
        VocabularyName="MAEC", VocabularyVersion=MAEC_VERSION
    ).first()
    if vocab is None:
        vocab = VOCABULARY(
            VocabularyName="MAEC",
            VocabularyVersion=MAEC_VERSION,
            CreatedDate=_now(),
        )
        xorcism_session.add(vocab)
        xorcism_session.flush()
        log(MODULE, f"VOCABULARY MAEC créé (ID={vocab.VocabularyID})")
    return vocab.VocabularyID


def _ensure_version(xorcism_session, version_value: str, vocab_id: int) -> int:
    from xorcism_python.models.xorcism import VERSION
    v = xorcism_session.query(VERSION).filter_by(VersionValue=version_value).first()
    if v is None:
        v = VERSION(VersionValue=version_value, VocabularyID=vocab_id, CreatedDate=_now())
        xorcism_session.add(v)
        xorcism_session.flush()
    return v.VersionID


def _ensure_enumeration_version(xorcism_session, enum_name: str, version_id: int, vocab_id: int) -> int:
    from xorcism_python.models.xorcism import ENUMERATIONVERSION
    ev = xorcism_session.query(ENUMERATIONVERSION).filter_by(
        EnumerationName=enum_name, VersionID=version_id
    ).first()
    if ev is None:
        ev = ENUMERATIONVERSION(
            EnumerationName=enum_name,
            VersionID=version_id,
            VocabularyID=vocab_id,
            CreatedDate=_now(),
        )
        xorcism_session.add(ev)
        xorcism_session.flush()
    return ev.EnumerationVersionID


# ─── Import of an enumeration ─────────────────────────────────────────────────

def _import_enumeration(session, model, name_col: str, desc_col: str,
                        simple_type_el: ET.Element, ev_id: int, vocab_id: int) -> int:
    """Inserts/completes the values of an <xs:simpleType>. Returns the number of values."""
    cols = _cols(model)
    has_desc = desc_col in cols
    has_ev = "EnumerationVersionID" in cols
    has_vocab = "VocabularyID" in cols
    has_created = "CreatedDate" in cols

    count = 0
    for restr_el in simple_type_el:
        if _local(restr_el.tag) != "restriction":
            continue
        for enum_el in restr_el:
            if _local(enum_el.tag) != "enumeration":
                continue
            value = (enum_el.get("value") or "").strip()
            if not value:
                continue

            flt = {name_col: value}
            if has_ev:
                flt["EnumerationVersionID"] = ev_id
            obj = session.query(model).filter_by(**flt).first()
            if obj is None:
                kwargs = {name_col: _trunc(value, 4000)}
                if has_ev:
                    kwargs["EnumerationVersionID"] = ev_id
                if has_vocab:
                    kwargs["VocabularyID"] = vocab_id
                if has_created:
                    kwargs["CreatedDate"] = _now()
                obj = model(**kwargs)
                session.add(obj)
                session.flush()

            # Description : <xs:enumeration><xs:annotation><xs:documentation>
            if has_desc:
                doc = next(
                    (d for d in enum_el.iter() if _local(d.tag) == "documentation"),
                    None,
                )
                doc_text = _clean(_text(doc))
                if doc_text:
                    setattr(obj, desc_col, _trunc(doc_text, 4000))

            count += 1
    return count


# ─── Orchestration ───────────────────────────────────────────────────────────

def parse_maec_xsd(xsd_path: str) -> None:
    log(MODULE, f"Parsing {xsd_path}")
    tree = ET.parse(xsd_path)
    root = tree.getroot()
    if _local(root.tag) != "schema":
        log(MODULE, f"[WARN] racine inattendue : {_local(root.tag)} (attendu schema)")

    simple_types = [c for c in root if _local(c.tag) == "simpleType"]
    log(MODULE, f"simpleType de premier niveau : {len(simple_types)}")

    with session_scope("XORCISM") as xorcism_session:
        vocab_id = _setup_vocabulary(xorcism_session)
        xorcism_session.commit()

    n_enum = n_values = n_skipped = 0
    with session_scope("XORCISM") as xorcism_session, \
         session_scope("XMALWARE") as malware_session:

        for st_el in simple_types:
            name = st_el.get("name", "") or ""
            if "Enum-" not in name:
                continue

            # "<EnumerationName>-<version>" (the C# does Split('-')[0] / [1])
            parts = name.split("-")
            enum_name = parts[0]
            version_value = parts[1] if len(parts) > 1 else ""

            mapping = ENUM_BY_NAME.get(enum_name)
            if mapping is None:
                log(MODULE, f"[WARN] Pas de correspondance pour {name} (ignoré)")
                n_skipped += 1
                continue

            table, name_col, bind = mapping
            model = _model_for(table, bind)
            if name_col not in _cols(model):
                log(MODULE, f"[WARN] Colonne {name_col} absente de {table} (ignoré)")
                n_skipped += 1
                continue
            desc_col = _resolve_desc_col(model, name_col)
            sess = malware_session if bind == "XMALWARE" else xorcism_session

            # VERSION + ENUMERATIONVERSION (always in XORCISM)
            version_id = _ensure_version(xorcism_session, version_value, vocab_id)
            ev_id = _ensure_enumeration_version(xorcism_session, enum_name, version_id, vocab_id)
            # ENUMERATIONVERSION must be visible before inserting the linked values
            xorcism_session.flush()

            nv = _import_enumeration(sess, model, name_col, desc_col, st_el, ev_id, vocab_id)
            n_enum += 1
            n_values += nv

            # Batch commit
            if n_enum % 20 == 0:
                xorcism_session.commit()
                malware_session.commit()
                log(MODULE, f"  {n_enum} énumérations, {n_values} valeurs…")

        xorcism_session.commit()
        malware_session.commit()

    log(MODULE, f"Import MAEC terminé : {n_enum} énumérations, {n_values} valeurs "
                f"({n_skipped} simpleType ignorés).")


def main() -> None:
    parser = argparse.ArgumentParser(description="Import MAEC (vocabulaires XSD) dans XORCISM.db / XMALWARE.db")
    parser.add_argument(
        "--xsd", default="maec_default_vocabularies.xsd",
        help="Chemin vers le XSD MAEC (défaut : maec_default_vocabularies.xsd)"
    )
    parser.add_argument(
        "--download", action="store_true",
        help="Télécharger le XSD depuis le dépôt MAEC si absent"
    )
    args = parser.parse_args()

    if args.download or not os.path.exists(args.xsd):
        if not os.path.exists(args.xsd):
            download_maec(args.xsd)

    parse_maec_xsd(args.xsd)


if __name__ == "__main__":
    main()
