/**
 * journeys_fr.ts — French translations for the compliance-journey catalogue (server/journeys.ts).
 * Keyed by the EXACT English source string so it also localizes already-materialized journey steps
 * (COMPLIANCEJOURNEYSTEP) on read. Auto-generated; see tools/gen_journey_fr.py. Other languages
 * fall back to English. */
export const JOURNEY_FR: Record<string, string> = {
  // ── EU AI Act (Regulation (EU) 2024/1689) ──
  "EU AI Act (Regulation (EU) 2024/1689)": "EU AI Act (Règlement (UE) 2024/1689)",
  "The EU Artificial Intelligence Act — the world's first horizontal, risk-based AI regulation. Obligations scale with risk: prohibited practices (Art. 5), high-risk AI systems (Art. 6 + Annex III) carrying the heaviest duties, transparency-risk systems (Art. 50) and minimal-risk. This journey walks a provider or deployer from AI governance and an AI-system inventory through risk classification, the Art. 9 risk-management system, technical documentation and the ancillary obligations (conformity assessment, CE marking, EU-database registration, post-market monitoring and serious-incident reporting). Import the EU AI Act control catalogue to track the obligations as controls.": "Le règlement européen sur l'intelligence artificielle — la première réglementation horizontale de l'IA fondée sur le risque. Les obligations croissent avec le risque : pratiques interdites (art. 5), systèmes d'IA à haut risque (art. 6 + annexe III) aux obligations les plus lourdes, systèmes à risque de transparence (art. 50) et risque minimal. Ce parcours conduit un fournisseur ou un déployeur de la gouvernance de l'IA et de l'inventaire des systèmes d'IA jusqu'à la classification du risque, le système de gestion des risques (art. 9), la documentation technique et les obligations annexes (évaluation de la conformité, marquage CE, enregistrement dans la base de l'UE, surveillance après commercialisation et signalement des incidents graves). Importez le catalogue de contrôles de l'EU AI Act pour suivre les obligations en tant que contrôles.",
  "9–18 months (phased: GPAI Aug 2025 · high-risk Aug 2026/2027)": "9–18 mois (par phases : IAUG août 2025 · haut risque août 2026/2027)",
  "Gouvernance & AI literacy": "Gouvernance & maîtrise de l'IA",
  "Cartographie des systèmes d'IA": "Cartographie des systèmes d'IA",
  "Classification du risque": "Classification du risque",
  "Gérer les risques": "Gérer les risques",
  "Documenter (Art. 11–15)": "Documenter (art. 11–15)",
  "Obligations annexes": "Obligations annexes",
  "Stand up an AI governance body, assign accountability and determine your role under the Act (provider / deployer / importer / distributor).": "Mettre en place une instance de gouvernance de l'IA, attribuer les responsabilités et déterminer votre rôle au titre du Règlement (fournisseur / déployeur / importateur / distributeur).",
  "AI literacy (Art. 4)": "Maîtrise de l'IA (art. 4)",
  "Ensure staff who operate or oversee AI systems have a sufficient level of AI literacy.": "S'assurer que le personnel qui exploite ou supervise des systèmes d'IA dispose d'un niveau suffisant de maîtrise de l'IA.",
  "Quality management system (Art. 17)": "Système de gestion de la qualité (art. 17)",
  "For high-risk AI, put in place the QMS covering processes, change control and responsibilities.": "Pour l'IA à haut risque, mettre en place le SGQ couvrant les processus, la gestion des changements et les responsabilités.",
  "Inventory AI systems & models": "Inventorier les systèmes & modèles d'IA",
  "Catalogue every AI system / model / agent in use or placed on the market, with purpose, data, owner and your role under the Act.": "Recenser chaque système / modèle / agent d'IA utilisé ou mis sur le marché, avec sa finalité, ses données, son propriétaire et votre rôle au titre du Règlement.",
  "Identify GPAI & third-party AI": "Identifier les IA à usage général & les IA tierces",
  "Flag general-purpose AI models (Art. 53–55) and AI obtained from third parties; track third-party AI risk in TPRM.": "Repérer les modèles d'IA à usage général (art. 53–55) et les IA fournies par des tiers ; suivre le risque IA tiers dans le TPRM.",
  "Screen for prohibited practices (Art. 5)": "Détecter les pratiques interdites (art. 5)",
  "Verify no AI system performs a prohibited practice (social scoring, manipulative techniques, untargeted facial-image scraping, etc.).": "Vérifier qu'aucun système d'IA n'exerce une pratique interdite (notation sociale, techniques manipulatrices, moissonnage non ciblé d'images faciales, etc.).",
  "Classify high-risk systems (Art. 6 + Annex III)": "Classer les systèmes à haut risque (art. 6 + annexe III)",
  "Determine which systems are high-risk (Annex III use-cases or safety components) — these carry the full obligation set.": "Déterminer quels systèmes sont à haut risque (cas d'usage de l'annexe III ou composants de sécurité) — ils portent l'ensemble des obligations.",
  "Transparency-risk & minimal-risk (Art. 50)": "Risque de transparence & risque minimal (art. 50)",
  "Identify limited-risk systems requiring transparency (chatbots, emotion recognition, deepfakes) and the minimal-risk remainder.": "Identifier les systèmes à risque limité soumis à transparence (agents conversationnels, reconnaissance des émotions, hypertrucages) et le reste à risque minimal.",
  "Risk-management system (Art. 9)": "Système de gestion des risques (art. 9)",
  "Run the continuous, iterative risk-management system across the AI lifecycle; record risks in the register.": "Exécuter le système de gestion des risques continu et itératif sur tout le cycle de vie de l'IA ; consigner les risques dans le registre.",
  "Data & data governance (Art. 10)": "Données & gouvernance des données (art. 10)",
  "Govern training/validation/test data quality, representativeness and bias examination.": "Gouverner la qualité, la représentativité et l'examen des biais des données d'entraînement / validation / test.",
  "Fundamental-rights impact assessment (Art. 27)": "Analyse d'impact sur les droits fondamentaux (art. 27)",
  "Where required (deployers of certain high-risk systems), perform the FRIA on affected persons.": "Lorsque requis (déployeurs de certains systèmes à haut risque), réaliser l'AIDF sur les personnes concernées.",
  "Map AI-specific threats": "Cartographier les menaces propres à l'IA",
  "Reference the Agentic AI Attack Matrix / SAIF and AI guardrails for AI-specific threats and mitigations.": "S'appuyer sur l'Agentic AI Attack Matrix / SAIF et les garde-fous IA pour les menaces et atténuations propres à l'IA.",
  "Technical documentation (Art. 11 + Annex IV)": "Documentation technique (art. 11 + annexe IV)",
  "Compile the technical documentation demonstrating conformity before placing the system on the market.": "Constituer la documentation technique démontrant la conformité avant la mise sur le marché du système.",
  "Record-keeping & logging (Art. 12)": "Tenue de registres & journalisation (art. 12)",
  "Ensure automatic logging of events over the system's lifetime for traceability.": "Assurer la journalisation automatique des événements sur toute la durée de vie du système à des fins de traçabilité.",
  "Transparency & instructions for use (Art. 13)": "Transparence & notice d'utilisation (art. 13)",
  "Provide deployers with clear instructions and the information needed for compliant operation.": "Fournir aux déployeurs des instructions claires et les informations nécessaires à une exploitation conforme.",
  "Human oversight (Art. 14)": "Contrôle humain (art. 14)",
  "Design and document effective human-oversight measures.": "Concevoir et documenter des mesures de contrôle humain effectives.",
  "Accuracy, robustness & cybersecurity (Art. 15)": "Exactitude, robustesse & cybersécurité (art. 15)",
  "Demonstrate appropriate accuracy, robustness and cybersecurity; harden and test the system.": "Démontrer une exactitude, une robustesse et une cybersécurité appropriées ; durcir et tester le système.",
  "Conformity assessment (Art. 43)": "Évaluation de la conformité (art. 43)",
  "Carry out the applicable conformity-assessment procedure for high-risk systems.": "Réaliser la procédure d'évaluation de la conformité applicable aux systèmes à haut risque.",
  "EU declaration of conformity & CE marking (Art. 47–48)": "Déclaration UE de conformité & marquage CE (art. 47–48)",
  "Draw up the EU declaration of conformity and affix the CE marking.": "Établir la déclaration UE de conformité et apposer le marquage CE.",
  "Register in the EU database (Art. 49 / 71)": "Enregistrement dans la base de données de l'UE (art. 49 / 71)",
  "Register the high-risk AI system (and yourself) in the EU database before placing it on the market.": "Enregistrer le système d'IA à haut risque (et vous-même) dans la base de données de l'UE avant la mise sur le marché.",
  "Post-market monitoring (Art. 72)": "Surveillance après commercialisation (art. 72)",
  "Operate a post-market monitoring system to collect and analyse performance data.": "Exploiter un système de surveillance après commercialisation pour collecter et analyser les données de performance.",
  "Serious-incident reporting (Art. 73)": "Signalement des incidents graves (art. 73)",
  "Wire the reporting of serious incidents and malfunctioning to the market-surveillance authority.": "Mettre en place le signalement des incidents graves et dysfonctionnements à l'autorité de surveillance du marché.",
  "12–18 months": "12–18 mois",
  "24h / 72h reporting to ENISA": "Notification à l'ENISA sous 24 h / 72 h",
  "2–6 months": "2–6 mois",
  "3PAO security assessment": "Évaluation de sécurité par le 3PAO",
  "3–6 months": "3–6 mois",
  "3–9 months": "3–9 mois",
  "3–9 months + observation window": "3–9 mois + fenêtre d'observation",
  "4–9 months": "4–9 mois",
  "6–12 months": "6–12 mois",
  "6–18 months": "6–18 mois",
  "72h breach notification": "Notification de violation sous 72 h",
  "9–18 months": "9–18 mois",
  "A FedRAMP-accredited 3PAO executes the SAP and produces the SAR.": "Un 3PAO accrédité FedRAMP exécute le SAP et produit le SAR.",
  "AI Management System (AIMS). The certifiable standard for governing the responsible development and use of AI systems.": "Système de management de l'IA (SMIA). La norme certifiable pour gouverner le développement et l'usage responsables des systèmes d'IA.",
  "AI Risk & Impact": "Risques & impacts IA",
  "AI governance & roles": "Gouvernance & rôles IA",
  "AI policies": "Politiques IA",
  "AI risk assessment": "Appréciation des risques IA",
  "AI system impact assessment": "Évaluation d'impact des systèmes d'IA",
  "AICPA Trust Services Criteria attestation. The de-facto report SaaS vendors provide to customers; Type II covers a 3–12 month operating period.": "Attestation selon les Trust Services Criteria de l'AICPA. Le rapport de référence que les fournisseurs SaaS remettent à leurs clients ; le Type II couvre une période d'exploitation de 3 à 12 mois.",
  "AIMS certification audit": "Audit de certification du SMIA",
  "AML / safeguarding": "LBC-FT / protection des avoirs",
  "ANSSI's national framework operationalising NIS 2 for France: 20 security objectives (the mandatory \"what\") with acceptable means of compliance (the \"how\"). Proportionality applies — objectives 1–15 bind Important (EI) and Essential (EE) entities; objectives 16–20 bind EE only. Structured by the Gouvernance / Protection / Défense / Résilience pillar model. (Working v2.5; import the ReCyF catalogue to track the measures as controls.)": "Référentiel national de l'ANSSI déclinant NIS 2 pour la France : 20 objectifs de sécurité (le « quoi » obligatoire) assortis de moyens acceptables de conformité (le « comment »). Le principe de proportionnalité s'applique — les objectifs 1 à 15 s'imposent aux entités importantes (EI) et essentielles (EE) ; les objectifs 16 à 20 ne s'imposent qu'aux EE. Structuré selon le modèle de piliers Gouvernance / Protection / Défense / Résilience. (Version de travail v2.5 ; importez le catalogue ReCyF pour suivre les mesures en tant que contrôles.)",
  "Access & change management": "Gestion des accès & des changements",
  "Address security in supplier relationships.": "Traiter la sécurité dans les relations avec les fournisseurs.",
  "Administer from dedicated, hardened resources — Essential entities.": "Administrer depuis des ressources dédiées et durcies — entités essentielles.",
  "Adopt risk-analysis and information-system security policies.": "Adopter des politiques d'analyse des risques et de sécurité des systèmes d'information.",
  "Adopt the AIMS policies (responsible AI, data, transparency…) — 10 AIMS policies are seedable.": "Adopter les politiques du SMIA (IA responsable, données, transparence…) — 10 politiques SMIA sont pré-chargeables.",
  "Applicability": "Applicabilité",
  "Apply secure baselines and verify them (configuration management).": "Appliquer des configurations sécurisées de référence et les vérifier (gestion des configurations).",
  "Apply the DORA ICT risk-management framework (MiCA references DORA).": "Appliquer le cadre de gestion des risques TIC de DORA (MiCA renvoie à DORA).",
  "Appoint a DPO / roles": "Désigner un DPO / rôles",
  "Appoint a Data Protection Officer (where required) and assign roles.": "Désigner un délégué à la protection des données (lorsque requis) et attribuer les rôles.",
  "Approve the top-level information-security policy and supporting policies.": "Approuver la politique de sécurité de l'information de haut niveau et les politiques associées.",
  "Assess": "Évaluer",
  "Assess (3PAO)": "Évaluer (3PAO)",
  "Assess concentration risk and document exit strategies for critical providers.": "Évaluer le risque de concentration et documenter les stratégies de sortie pour les prestataires critiques.",
  "Assess control effectiveness and record results.": "Évaluer l'efficacité des mesures et consigner les résultats.",
  "Assess controls (800-53A)": "Évaluer les mesures (800-53A)",
  "Assess risks of the AI systems (safety, bias, robustness, privacy, security).": "Apprécier les risques des systèmes d'IA (sûreté, biais, robustesse, vie privée, sécurité).",
  "Asset & dependency mapping": "Cartographie des actifs & dépendances",
  "Asset management": "Gestion des actifs",
  "Assign AIMS roles, accountability and an AI governance body (clause 5).": "Attribuer les rôles du SMIA, la responsabilité et constituer une instance de gouvernance de l'IA (chapitre 5).",
  "Audit & Certification": "Audit & certification",
  "Audit the security of information systems — Essential entities.": "Auditer la sécurité des systèmes d'information — entités essentielles.",
  "Author the SSP": "Rédiger le SSP",
  "Authorization": "Autorisation",
  "Authorization (ATO)": "Autorisation (ATO)",
  "Authorization application": "Demande d'agrément",
  "Authorize & ConMon": "Autoriser & ConMon",
  "Authorize & Monitor": "Autoriser & surveiller",
  "Authorize (ATO)": "Autoriser (ATO)",
  "Awareness & training": "Sensibilisation & formation",
  "Awareness training": "Formation de sensibilisation",
  "Backup management, disaster recovery and crisis management.": "Gestion des sauvegardes, reprise après sinistre et gestion de crise.",
  "Breach & Accountability": "Violations & responsabilité",
  "Build the Article 30 record of processing activities.": "Constituer le registre des activités de traitement (article 30).",
  "Build the asset inventory": "Constituer l'inventaire des actifs",
  "Business continuity": "Continuité d'activité",
  "Capture internal/external issues and the requirements of interested parties (clause 4).": "Recenser les enjeux internes/externes et les exigences des parties intéressées (chapitre 4).",
  "Catalogue AI systems / models / agents, their purpose, data and owners.": "Cataloguer les systèmes / modèles / agents d'IA, leur finalité, leurs données et leurs propriétaires.",
  "Categorize": "Catégoriser",
  "Categorize the system (FIPS 199)": "Catégoriser le système (FIPS 199)",
  "Classify ICT incidents": "Classifier les incidents TIC",
  "Classify ICT-related incidents and cyber threats per the RTS criteria.": "Classifier les incidents liés aux TIC et les cybermenaces selon les critères des RTS.",
  "Classify the product": "Classer le produit",
  "Close non-conformities, gather the evidence pack and confirm audit readiness.": "Clôturer les non-conformités, constituer le dossier de preuves et confirmer l'état de préparation à l'audit.",
  "Collect evidence": "Collecter les preuves",
  "Compile the technical documentation, EU declaration of conformity and affix CE marking.": "Constituer la documentation technique, la déclaration UE de conformité et apposer le marquage CE.",
  "Concentration & exit": "Concentration & sortie",
  "Configure regulator notifications": "Configurer les notifications au régulateur",
  "Conformity & CE": "Conformité & marquage CE",
  "Conformity assessment": "Évaluation de la conformité",
  "Continuous monitoring": "Surveillance continue",
  "Continuous monitoring & reporting": "Surveillance & reporting continus",
  "Control physical access to premises hosting the information systems.": "Maîtriser les accès physiques aux locaux hébergeant les systèmes d'information.",
  "Controls & Policies": "Mesures & politiques",
  "Controls Implementation": "Mise en œuvre des mesures",
  "Coordinated disclosure": "Divulgation coordonnée",
  "Corrective actions & readiness": "Actions correctives & préparation",
  "Crisis exercises": "Exercices de crise",
  "DPIA": "AIPD",
  "Data & model governance": "Gouvernance des données & des modèles",
  "Data inventory & flows": "Inventaire & flux de données",
  "Data-subject rights": "Droits des personnes concernées",
  "Decide treatment (mitigate/accept/transfer/avoid) and record it in the risk register.": "Décider du traitement (réduire/accepter/transférer/éviter) et le consigner dans le registre des risques.",
  "Define measurable security objectives and the plan to achieve them (clause 6).": "Définir des objectifs de sécurité mesurables et le plan pour les atteindre (chapitre 6).",
  "Define the AIMS scope": "Définir le périmètre du SMIA",
  "Define the ISMS scope": "Définir le périmètre du SMSI",
  "Define the authorization boundary and asset inventory.": "Définir le périmètre d'autorisation et l'inventaire des actifs.",
  "Define the boundary": "Définir le périmètre",
  "Define the organizational profile: current vs. target outcomes and tier.": "Définir le profil organisationnel : résultats actuels vs cibles et palier (tier).",
  "Deliver awareness and role-based training.": "Dispenser une sensibilisation et des formations adaptées aux rôles.",
  "Deliver monthly ConMon: scans, POA&M updates and annual assessment.": "Assurer le ConMon mensuel : scans, mises à jour du POA&M et évaluation annuelle.",
  "Demonstrate accountability": "Démontrer la responsabilité (accountability)",
  "Describe the system, boundaries, infrastructure, data and subservice organizations.": "Décrire le système, ses limites, l'infrastructure, les données et les organisations de sous-traitance.",
  "Detect (DE)": "Détecter (DE)",
  "Detect and react to security incidents (process, classification, handling).": "Détecter et réagir aux incidents de sécurité (processus, classification, traitement).",
  "Determine and document the lawful basis for each processing activity.": "Déterminer et documenter la base légale de chaque traitement.",
  "Determine entity type": "Déterminer le type d'entité",
  "Determine if the product with digital elements is default / important (class I/II) / critical.": "Déterminer si le produit comportant des éléments numériques est par défaut / important (classe I/II) / critique.",
  "Determine impact level": "Déterminer le niveau d'impact",
  "Determine the impact level (Low / Moderate / High) for confidentiality, integrity, availability.": "Déterminer le niveau d'impact (faible / modéré / élevé) pour la confidentialité, l'intégrité, la disponibilité.",
  "Determine your role": "Déterminer votre rôle",
  "Digital Operational Resilience Act for EU financial entities: ICT risk management, incident reporting, resilience testing and third-party (ICT) oversight.": "Règlement sur la résilience opérationnelle numérique (DORA) pour les entités financières de l'UE : gestion des risques TIC, notification des incidents, tests de résilience et supervision des tiers (TIC).",
  "Digital resilience testing": "Tests de résilience numérique",
  "Document": "Documenter",
  "Document how each control is implemented in the SSP.": "Documenter dans le SSP la mise en œuvre de chaque mesure.",
  "Document the boundaries of the AI management system and the AI systems in scope.": "Documenter les limites du système de management de l'IA et les systèmes d'IA dans le périmètre.",
  "Document the boundaries: business units, locations, assets and the perimeter the ISMS covers.": "Documenter les limites : unités métier, sites, actifs et le périmètre couvert par le SMSI.",
  "Document the system boundary, data flows and inventory.": "Documenter le périmètre du système, les flux de données et l'inventaire.",
  "EU General Data Protection Regulation: lawful processing of personal data, data-subject rights, DPIAs and 72h breach notification.": "Règlement général sur la protection des données (RGPD) : licéité du traitement des données personnelles, droits des personnes concernées, AIPD et notification des violations sous 72 h.",
  "EU directive raising the cybersecurity baseline for essential and important entities, with management accountability and strict incident reporting.": "Directive européenne relevant le niveau de cybersécurité des entités essentielles et importantes, avec responsabilité de la direction et notification stricte des incidents.",
  "Engage a licensed CPA firm to perform the SOC 2 Type II examination.": "Mandater un cabinet CPA agréé pour réaliser l'examen SOC 2 de Type II.",
  "Engage the certification body / auditor and complete the formal assessment.": "Mandater l'organisme de certification / l'auditeur et réaliser l'évaluation formelle.",
  "Essential Requirements (Annex I)": "Exigences essentielles (Annexe I)",
  "Establish a coordinated vulnerability-disclosure policy and contact.": "Établir une politique de divulgation coordonnée des vulnérabilités et un point de contact.",
  "Establish governance": "Établir la gouvernance",
  "Establish lawful basis": "Établir la base légale",
  "Establish the ICT risk-management framework with board accountability (Ch. II).": "Établir le cadre de gestion des risques TIC avec responsabilité de l'organe de direction (chap. II).",
  "Establish the inventory of information assets in scope with owners and criticality.": "Établir l'inventaire des actifs informationnels du périmètre avec leurs propriétaires et leur criticité.",
  "Establish whether you are a token issuer (ART/EMT) or a crypto-asset service provider (CASP).": "Déterminer si vous êtes un émetteur de jetons (ART/EMT) ou un prestataire de services sur crypto-actifs (PSCA).",
  "Establish whether you are an essential or important entity and which sectors apply.": "Déterminer si vous êtes une entité essentielle ou importante et quels secteurs s'appliquent.",
  "European Union": "Union européenne",
  "Framework": "Référentiel",
  "Gather evidence for each control to support the audit.": "Rassembler les preuves pour chaque mesure afin d'étayer l'audit.",
  "Gather evidence of AIMS operation for the audit.": "Rassembler les preuves de fonctionnement du SMIA pour l'audit.",
  "Generate and maintain a Software Bill of Materials (CycloneDX/SPDX).": "Générer et maintenir une nomenclature logicielle (SBOM, CycloneDX/SPDX).",
  "Govern (GV)": "Gouverner (GV)",
  "Govern training data, model documentation and change management.": "Gouverner les données d'entraînement, la documentation des modèles et la gestion des changements.",
  "Governance & Accountability": "Gouvernance & responsabilité",
  "Governance & Conduct": "Gouvernance & conduite",
  "Governance arrangements": "Dispositifs de gouvernance",
  "Harden configurations": "Durcir les configurations",
  "Hold a management review of objectives, risks, incidents, audit results and improvement actions.": "Tenir une revue de direction sur les objectifs, risques, incidents, résultats d'audit et actions d'amélioration.",
  "ICT & Operational Resilience (DORA)": "Résilience TIC & opérationnelle (DORA)",
  "ICT Risk Management": "Gestion des risques TIC",
  "ICT risk management": "Gestion des risques TIC",
  "ICT risk-management framework": "Cadre de gestion des risques TIC",
  "ICT third-party register": "Registre des prestataires tiers TIC",
  "Identify (ID)": "Identifier (ID)",
  "Identify and assess cybersecurity risks.": "Identifier et apprécier les risques de cybersécurité.",
  "Identity management, access control, data security, platform security, awareness.": "Gestion des identités, contrôle d'accès, sécurité des données, sécurité des plateformes, sensibilisation.",
  "Implement & Document": "Mettre en œuvre & documenter",
  "Implement 800-53 baseline": "Mettre en œuvre le socle 800-53",
  "Implement AML/CFT and client-asset safeguarding controls.": "Mettre en œuvre des contrôles LBC-FT et de protection des avoirs des clients.",
  "Implement Annex A AIMS controls": "Mettre en œuvre les mesures de l'Annexe A du SMIA",
  "Implement Annex A controls": "Mettre en œuvre les mesures de l'Annexe A",
  "Implement Art. 21 measures: crypto, access control, MFA, asset & vulnerability handling.": "Mettre en œuvre les mesures de l'art. 21 : chiffrement, contrôle d'accès, MFA, gestion des actifs & des vulnérabilités.",
  "Implement appropriate technical and organizational measures.": "Mettre en œuvre des mesures techniques et organisationnelles appropriées.",
  "Implement controls": "Mettre en œuvre les mesures",
  "Implement controls for ICT security, identity and resilience.": "Mettre en œuvre des mesures de sécurité TIC, d'identité et de résilience.",
  "Implement protections": "Mettre en œuvre les protections",
  "Implement the Annex I Part I security requirements across the lifecycle.": "Mettre en œuvre les exigences de sécurité de l'Annexe I, partie I, sur tout le cycle de vie.",
  "Implement the FedRAMP control baseline for the chosen impact level.": "Mettre en œuvre le socle de mesures FedRAMP pour le niveau d'impact retenu.",
  "Implement the ISO 42001 Annex A controls across the AI lifecycle.": "Mettre en œuvre les mesures de l'Annexe A d'ISO 42001 sur tout le cycle de vie de l'IA.",
  "Implement the selected Annex A (organizational/people/physical/technological) controls.": "Mettre en œuvre les mesures retenues de l'Annexe A (organisationnelles/humaines/physiques/technologiques).",
  "Implement the selected controls and record implementation status.": "Mettre en œuvre les mesures retenues et consigner leur état de mise en œuvre.",
  "Incident Management & Reporting": "Gestion & notification des incidents",
  "Incident Reporting (Art. 23)": "Notification des incidents (art. 23)",
  "Incident management": "Gestion des incidents",
  "Incident reporting": "Notification des incidents",
  "Incident response": "Réponse aux incidents",
  "Information Security Management System (ISMS). The certifiable baseline for security governance, risk treatment and Annex A controls.": "Système de management de la sécurité de l'information (SMSI). Le socle certifiable pour la gouvernance de la sécurité, le traitement des risques et les mesures de l'Annexe A.",
  "Information sharing": "Partage d'informations",
  "Integrate digital security into HR (onboarding/offboarding, awareness, cyber-hygiene).": "Intégrer la sécurité numérique à la gestion des ressources humaines (arrivées/départs, sensibilisation, cyberhygiène).",
  "Internal audit": "Audit interne",
  "Inventory AI systems": "Inventorier les systèmes d'IA",
  "Inventory assets, data and suppliers in scope.": "Inventorier les actifs, les données et les fournisseurs du périmètre.",
  "Inventory components and third-party / open-source dependencies.": "Inventorier les composants et les dépendances tierces / open source.",
  "Inventory personal data, systems and cross-border flows.": "Inventorier les données personnelles, les systèmes et les flux transfrontaliers.",
  "Inventory the boundary": "Inventorier le périmètre d'autorisation",
  "Justify the applicability of the 93 Annex A controls and link them to risks.": "Justifier l'applicabilité des 93 mesures de l'Annexe A et les relier aux risques.",
  "Keep systems mastered: inventory, secure baselines and configuration control.": "Maîtriser les systèmes : inventaire, configurations sécurisées de référence et contrôle des configurations.",
  "Leadership & AI Policy": "Direction & politique IA",
  "Leadership & Governance": "Direction & gouvernance",
  "Maintain a list of all activities/services and the information systems supporting them.": "Tenir à jour une liste de l'ensemble des activités/services et des systèmes d'information qui les supportent.",
  "Maintain business-continuity and disaster-recovery capability (backups, RTO/RPO).": "Maintenir une capacité de continuité d'activité et de reprise (sauvegardes, RTO/RPO).",
  "Maintain evidence of compliance for the supervisory authority.": "Conserver les preuves de conformité pour l'autorité de contrôle.",
  "Maintain ongoing monitoring and regulatory reporting obligations.": "Assurer la surveillance continue et les obligations de reporting réglementaire.",
  "Maintain the register of information on ICT third-party arrangements.": "Tenir à jour le registre d'informations sur les accords avec les prestataires tiers de services TIC.",
  "Major-incident reporting": "Notification des incidents majeurs",
  "Manage subservice organizations and vendor risk.": "Gérer les organisations de sous-traitance et le risque fournisseurs.",
  "Manage user identities and access (least privilege, lifecycle).": "Gérer les identités et les accès des utilisateurs (moindre privilège, cycle de vie).",
  "Management bodies approve measures and complete cybersecurity training (Art. 20).": "Les organes de direction approuvent les mesures et suivent une formation en cybersécurité (art. 20).",
  "Management oversight & training": "Supervision par la direction & formation",
  "Management review": "Revue de direction",
  "Mandatory cybersecurity for products with digital elements: secure-by-design requirements, SBOM, vulnerability handling, conformity assessment and CE marking.": "Cybersécurité obligatoire pour les produits comportant des éléments numériques : exigences de sécurité dès la conception, SBOM, traitement des vulnérabilités, évaluation de la conformité et marquage CE.",
  "Map & Lawfulness": "Cartographie & licéité",
  "Map ICT assets and the business functions they support.": "Cartographier les actifs TIC et les fonctions métier qu'ils supportent.",
  "Map controls to the TSC": "Relier les mesures aux TSC",
  "Map digital elements & dependencies": "Cartographier les éléments numériques & dépendances",
  "Map suppliers/providers and secure ICT supply-chain relationships contractually.": "Cartographier les prestataires/fournisseurs et sécuriser contractuellement la chaîne d'approvisionnement TIC.",
  "Map to AI threats": "Relier aux menaces IA",
  "Map your controls to the Common Criteria (CC1–CC9) and the selected categories.": "Relier vos mesures aux Common Criteria (CC1–CC9) et aux catégories retenues.",
  "Markets in Crypto-Assets regulation for issuers and crypto-asset service providers (CASPs): authorization, governance and ICT/operational resilience (via DORA).": "Règlement sur les marchés de crypto-actifs (MiCA) pour les émetteurs et les prestataires de services sur crypto-actifs (PSCA) : agrément, gouvernance et résilience opérationnelle/TIC (via DORA).",
  "Master administration (privileged accounts, admin practices).": "Maîtriser l'administration (comptes à privilèges, pratiques d'administration).",
  "Measure & improve": "Mesurer & améliorer",
  "Measure & report": "Mesurer & rendre compte",
  "Monitor AI performance": "Surveiller la performance de l'IA",
  "Monitor AI systems in operation (drift, incidents, human oversight).": "Surveiller les systèmes d'IA en exploitation (dérive, incidents, supervision humaine).",
  "Monitoring & incidents": "Supervision & incidents",
  "NIST Cybersecurity Framework 2.0. A voluntary outcome-based framework across six functions: Govern, Identify, Protect, Detect, Respond, Recover.": "NIST Cybersecurity Framework 2.0. Un cadre volontaire orienté résultats articulé autour de six fonctions : Gouverner, Identifier, Protéger, Détecter, Répondre, Rétablir.",
  "Observation period": "Période d'observation",
  "Obtain top-management commitment, assign ISMS roles and responsibilities (clause 5).": "Obtenir l'engagement de la direction générale, attribuer les rôles et responsabilités du SMSI (chapitre 5).",
  "Ongoing Compliance": "Conformité continue",
  "Operate & monitor": "Exploiter & surveiller",
  "Operate ICT-incident classification and reporting.": "Assurer la classification et la notification des incidents TIC.",
  "Operate access, rectification, erasure and portability request handling.": "Traiter les demandes d'accès, de rectification, d'effacement et de portabilité.",
  "Operate controls consistently across the audit window and collect evidence each period.": "Exploiter les mesures de façon constante sur la fenêtre d'audit et collecter les preuves à chaque période.",
  "Operate incident management, analysis and reporting.": "Exploiter la gestion, l'analyse et la notification des incidents.",
  "Operate initial / intermediate / final reporting to the competent authority.": "Assurer les notifications initiale / intermédiaire / finale à l'autorité compétente.",
  "Operate logical access, onboarding/offboarding and change controls.": "Exploiter les contrôles d'accès logiques, d'arrivée/départ et de gestion des changements.",
  "Operate monitoring and adverse-event analysis.": "Exploiter la supervision et l'analyse des événements indésirables.",
  "Operate monitoring, alerting and incident response (CC7).": "Exploiter la supervision, l'alerte et la réponse aux incidents (CC7).",
  "Operate ongoing monitoring of controls and risk.": "Assurer la surveillance continue des mesures et du risque.",
  "Operate security supervision / detection (log collection, monitoring) — Essential entities.": "Exploiter la supervision / détection de sécurité (collecte de journaux, surveillance) — entités essentielles.",
  "Operate the Controls": "Exploiter les mesures",
  "Operate the breach-detection and 72h notification process.": "Assurer la détection des violations et le processus de notification sous 72 h.",
  "Operate the incident process and meet response SLAs.": "Exploiter le processus de gestion des incidents et respecter les SLA de réponse.",
  "Operate vulnerability and patch management with risk-based SLAs.": "Exploiter la gestion des vulnérabilités et des correctifs avec des SLA fondés sur le risque.",
  "Operate vulnerability identification, remediation and security updates.": "Assurer l'identification des vulnérabilités, leur correction et les mises à jour de sécurité.",
  "Operations & Evidence": "Exploitation & preuves",
  "Participate in threat-intelligence information sharing.": "Participer au partage d'informations de renseignement sur les menaces.",
  "Perform a NIST 800-30 risk assessment to drive tailoring.": "Réaliser une appréciation des risques NIST 800-30 pour guider l'adaptation.",
  "Perform and document a risk assessment (CC3).": "Réaliser et documenter une appréciation des risques (CC3).",
  "Perform and document the product cybersecurity risk assessment.": "Réaliser et documenter l'appréciation des risques de cybersécurité du produit.",
  "Plan advanced TLPT for entities in scope.": "Planifier des TLPT avancés pour les entités concernées.",
  "Plan and rehearse recovery (crisis exercises, BCP).": "Planifier et tester le rétablissement (exercices de crise, PCA).",
  "Plan and run an internal audit of the management system; record findings and corrective actions.": "Planifier et réaliser un audit interne du système de management ; consigner les constats et actions correctives.",
  "Policies & procedures": "Politiques & procédures",
  "Prepare": "Préparer",
  "Prepare the authorization / notification dossier for the competent authority.": "Préparer le dossier d'agrément / de notification pour l'autorité compétente.",
  "Privacy notices & consent": "Mentions d'information & consentement",
  "Processor agreements": "Contrats de sous-traitance",
  "Produce the SBOM": "Produire le SBOM",
  "Produce the authorization package and obtain the authorization decision.": "Produire le dossier d'autorisation et obtenir la décision d'autorisation.",
  "Produce the crypto-asset whitepaper and required client disclosures (where applicable).": "Produire le livre blanc du crypto-actif et les informations à fournir aux clients (le cas échéant).",
  "Product Scope": "Périmètre produit",
  "Protect & Assess": "Protéger & évaluer",
  "Protect (PR)": "Protéger (PR)",
  "Protect systems against malware (EDR/AV, scanning).": "Protéger les systèmes contre les codes malveillants (EDR/antivirus, analyse).",
  "Protection & prevention": "Protection & prévention",
  "Provide the required policies and procedures.": "Fournir les politiques et procédures requises.",
  "Publish privacy notices and manage consent.": "Publier les mentions d'information et gérer le consentement.",
  "Publish the policies the TSC expect (access, change, incident, vendor, BCP…).": "Publier les politiques attendues par les TSC (accès, changement, incident, fournisseurs, PCA…).",
  "Put Article 28 data-processing agreements in place with processors.": "Conclure des contrats de sous-traitance (article 28) avec les sous-traitants.",
  "Put in place sound governance, fit-and-proper management and conflict-of-interest controls.": "Mettre en place une gouvernance saine, une direction compétente et honorable et des contrôles des conflits d'intérêts.",
  "Readiness & Audit": "Préparation & audit",
  "Readiness assessment (Type I)": "Évaluation de préparation (Type I)",
  "Records of processing (ROPA)": "Registre des traitements (ROPA)",
  "Recovery & resilience": "Rétablissement & résilience",
  "Reference the Agentic AI Attack Matrix / SAIF for AI-specific threats and mitigations.": "S'appuyer sur l'Agentic AI Attack Matrix / SAIF pour les menaces et mesures spécifiques à l'IA.",
  "Register with the authority": "S'enregistrer auprès de l'autorité",
  "Register with the national competent authority / CSIRT as required.": "S'enregistrer auprès de l'autorité nationale compétente / du CSIRT selon les exigences.",
  "Regulation": "Réglementation",
  "Rehearse operational-resilience scenarios.": "Répéter des scénarios de résilience opérationnelle.",
  "Remediate & POA&M": "Corriger & POA&M",
  "Remediate findings and maintain the POA&M.": "Corriger les constats et maintenir le POA&M.",
  "Reporting process (24h / 72h / 1 month)": "Processus de notification (24 h / 72 h / 1 mois)",
  "Resilience Testing": "Tests de résilience",
  "Resilience testing": "Tests de résilience",
  "Respond (RS) & Recover (RC)": "Répondre (RS) & Rétablir (RC)",
  "Rights & Governance": "Droits & gouvernance",
  "Risk Management": "Gestion des risques",
  "Risk analysis & policies": "Analyse des risques & politiques",
  "Risk assessment": "Appréciation des risques",
  "Risk treatment plan": "Plan de traitement des risques",
  "Risk-Management Measures (Art. 21)": "Mesures de gestion des risques (art. 21)",
  "Roll out awareness training and phishing simulations for staff.": "Déployer des formations de sensibilisation et des simulations d'hameçonnage pour le personnel.",
  "Run Data Protection Impact Assessments for high-risk processing.": "Réaliser des analyses d'impact relatives à la protection des données pour les traitements à haut risque.",
  "Run a readiness/gap assessment and remediate before the observation window.": "Réaliser une évaluation de préparation/d'écarts et corriger avant la fenêtre d'observation.",
  "Run a risk-based approach (analysis & treatment) — Essential entities.": "Mettre en œuvre une approche par les risques (analyse & traitement) — entités essentielles.",
  "Run an information-security risk assessment (EBIOS RM or NIST 800-30) to identify and rate risks.": "Réaliser une appréciation des risques de sécurité de l'information (EBIOS RM ou NIST 800-30) pour identifier et coter les risques.",
  "Run digital operational-resilience testing.": "Réaliser des tests de résilience opérationnelle numérique.",
  "Run exercises, tests and drills to validate readiness.": "Réaliser des exercices, tests et entraînements pour valider l'état de préparation.",
  "Run monitoring/logging and keep the ISMS operating; collect operational records.": "Assurer la supervision/journalisation et le maintien en condition du SMSI ; collecter les enregistrements d'exploitation.",
  "Run security awareness training for personnel (CC1/CC2).": "Dispenser une formation de sensibilisation à la sécurité au personnel (CC1/CC2).",
  "Run the AI impact assessment on individuals and society (Annex B / clause 6).": "Réaliser l'évaluation d'impact de l'IA sur les individus et la société (Annexe B / chapitre 6).",
  "Run the applicable conformity-assessment procedure (self / notified body).": "Réaliser la procédure d'évaluation de la conformité applicable (auto-évaluation / organisme notifié).",
  "Run the testing programme (vulnerability scans, scenario tests).": "Exécuter le programme de tests (scans de vulnérabilités, tests de scénarios).",
  "Scope & AI Inventory": "Périmètre & inventaire IA",
  "Scope & Authorization": "Périmètre & agrément",
  "Scope & Context": "Périmètre & contexte",
  "Scope & Criteria": "Périmètre & critères",
  "Score the profile gap and track improvement over time.": "Coter l'écart de profil et suivre l'amélioration dans le temps.",
  "Secure leadership commitment": "Obtenir l'engagement de la direction",
  "Secure remote access (MFA, VPN, exposure control).": "Sécuriser les accès distants (MFA, VPN, maîtrise de l'exposition).",
  "Secure the architecture (segmentation, interconnections, hardening).": "Sécuriser l'architecture (cloisonnement, interconnexions, durcissement).",
  "Secure the configuration of system resources — Essential entities.": "Sécuriser la configuration des ressources des systèmes — entités essentielles.",
  "Secure-by-design & by-default": "Sécurité dès la conception & par défaut",
  "Security & privacy controls catalogue and the RMF. The control baseline behind FedRAMP and most US federal authorizations.": "Catalogue de mesures de sécurité et de protection de la vie privée et cadre RMF. Le socle de mesures qui sous-tend FedRAMP et la plupart des autorisations fédérales américaines.",
  "Security awareness": "Sensibilisation à la sécurité",
  "Security is mandatory; add Availability, Confidentiality, Processing Integrity and/or Privacy.": "Le critère Sécurité est obligatoire ; ajouter Disponibilité, Confidentialité, Intégrité du traitement et/ou Vie privée.",
  "Security of processing (Art. 32)": "Sécurité du traitement (art. 32)",
  "Select": "Sélectionner",
  "Select Low / Moderate / High (or LI-SaaS) and the authorization path (Agency / JAB).": "Choisir Faible / Modéré / Élevé (ou LI-SaaS) et la voie d'autorisation (agence / JAB).",
  "Select Trust Services Criteria": "Choisir les Trust Services Criteria",
  "Select the Low/Moderate/High baseline and tailor it.": "Sélectionner le socle Faible/Modéré/Élevé et l'adapter.",
  "Select the control baseline": "Sélectionner le socle de mesures",
  "Set current & target profiles": "Définir les profils actuel & cible",
  "Set objectives & plan": "Définir les objectifs & le plan",
  "Set the cybersecurity strategy, roles, policy and risk-management expectations.": "Définir la stratégie de cybersécurité, les rôles, la politique et les attentes en matière de gestion des risques.",
  "Set the information-security policy": "Définir la politique de sécurité de l'information",
  "Set up cyber-crisis management and secure emergency communications.": "Mettre en place la gestion des crises d'origine cyber et des communications d'urgence sécurisées.",
  "Set up early warning (24h), incident notification (72h) and final report (1 month).": "Mettre en place l'alerte précoce (24 h), la notification d'incident (72 h) et le rapport final (1 mois).",
  "Set up reporting of actively-exploited vulnerabilities and severe incidents to ENISA/CSIRT.": "Mettre en place la notification des vulnérabilités activement exploitées et des incidents graves à l'ENISA/au CSIRT.",
  "Set up the digital-security governance, PSSI and conformity-management framework under the executive's responsibility.": "Mettre en place la gouvernance de la sécurité numérique, la PSSI et le cadre de gestion de la conformité sous la responsabilité du dirigeant.",
  "Stage 1 & Stage 2 certification audit": "Audit de certification (étapes 1 & 2)",
  "Statement of Applicability (SoA)": "Déclaration d'applicabilité (DdA)",
  "Submit the package for the Agency/JAB authorization decision.": "Soumettre le dossier pour la décision d'autorisation de l'agence/du JAB.",
  "Supply-chain security": "Sécurité de la chaîne d'approvisionnement",
  "System Security Plan (SSP)": "Plan de sécurité du système (SSP)",
  "Technical & organizational measures": "Mesures techniques & organisationnelles",
  "Technical documentation & CE marking": "Documentation technique & marquage CE",
  "Third-Party Risk": "Risque lié aux tiers",
  "Threat-led penetration testing (TLPT)": "Tests d'intrusion fondés sur la menace (TLPT)",
  "Track conformity to the NIS2 measures and report to leadership.": "Suivre la conformité aux mesures NIS2 et en rendre compte à la direction.",
  "Track weaknesses and remediation in a Plan of Action & Milestones.": "Suivre les faiblesses et leur correction dans un Plan of Action & Milestones (POA&M).",
  "Type II examination": "Examen de Type II",
  "US government authorization for cloud services, built on NIST 800-53 baselines, assessed by a 3PAO and authorized (JAB/Agency).": "Autorisation du gouvernement américain pour les services cloud, fondée sur les socles NIST 800-53, évaluée par un 3PAO et autorisée (JAB/agence).",
  "Understand context & interested parties": "Comprendre le contexte & les parties intéressées",
  "United States": "États-Unis",
  "Vendor management": "Gestion des fournisseurs",
  "Vulnerability & patch management": "Gestion des vulnérabilités & des correctifs",
  "Vulnerability Handling (Annex I Part II)": "Traitement des vulnérabilités (Annexe I, partie II)",
  "Vulnerability management": "Gestion des vulnérabilités",
  "Whitepaper & disclosures": "Livre blanc & informations à publier",
  "Wire the CSIRT/authority notification workflow.": "Mettre en place le flux de notification au CSIRT/à l'autorité.",
  "Write the System Security Plan with the FedRAMP templates and attachments.": "Rédiger le plan de sécurité du système avec les modèles et annexes FedRAMP.",
  "Write the system description": "Rédiger la description du système",
  // ── AI Security Management (AI-TRiSM) journey ──
  "AI Security Management (AI-TRiSM)": "Gestion de la sécurité de l'IA (AI-TRiSM)",
  "An end-to-end program to secure and govern AI: stand up AI governance and policy, inventory your AI systems and the non-human identities behind them, comply with the AI standards (ISO/IEC 42001 + the CSA AI Controls Matrix), assess third-party AI with the AICM AI-CAIQ questionnaire, and continuously monitor and guardrail AI at runtime via the XOR agent. Spans governance → identities → compliance → third-party → runtime assurance.": "Un programme de bout en bout pour sécuriser et gouverner l'IA : mettre en place la gouvernance et les politiques IA, inventorier vos systèmes IA et les identités non humaines qui les font fonctionner, vous conformer aux normes IA (ISO/IEC 42001 + la matrice de contrôles IA de la CSA), évaluer l'IA des tiers avec le questionnaire AI-CAIQ de l'AICM, et surveiller et encadrer l'IA en continu au runtime via l'agent XOR. Couvre gouvernance → identités → conformité → tiers → assurance au runtime.",
  "Govern": "Gouverner",
  "Inventory & Identities": "Inventaire et identités",
  "Comply with the AI standards": "Se conformer aux normes IA",
  "Third-party AI risk (TPRM)": "Risque IA des tiers (TPRM)",
  "Monitor & Guardrail (runtime, via the agent)": "Surveiller et encadrer (runtime, via l'agent)",
  "Assure & Improve": "Assurer et améliorer",
  "Establish AI governance & roles": "Établir la gouvernance et les rôles IA",
  "Set up the AI governance body, accountability (RACI) and a named AI security/ethics owner.": "Mettre en place l'instance de gouvernance IA, la responsabilité (RACI) et un responsable nommé de la sécurité/éthique de l'IA.",
  "AI policy framework": "Cadre de politiques IA",
  "Adopt the AI policies (responsible AI, acceptable use, data, transparency, human oversight) — 10 AIMS policies are seedable.": "Adopter les politiques IA (IA responsable, usage acceptable, données, transparence, supervision humaine) — 10 politiques SMIA sont préchargeables.",
  "AI risk appetite & register": "Appétit pour le risque IA et registre",
  "Define AI risk appetite and open an AI risk register (bias, safety, robustness, privacy, security, misuse).": "Définir l'appétit pour le risque IA et ouvrir un registre des risques IA (biais, sûreté, robustesse, vie privée, sécurité, usage abusif).",
  "Inventory AI systems, models & agents": "Inventorier les systèmes, modèles et agents IA",
  "Catalogue every AI system / model / agent, its purpose, data and owner.": "Cataloguer chaque système / modèle / agent IA, son objectif, ses données et son propriétaire.",
  "Govern non-human identities (NHI)": "Gouverner les identités non humaines (NHI)",
  "Inventory and constrain the service accounts, API keys and agent identities that run or serve AI — least privilege, rotation, lifecycle.": "Inventorier et encadrer les comptes de service, clés d'API et identités d'agents qui exécutent ou servent l'IA — moindre privilège, rotation, cycle de vie.",
  "Map AI assets & data flows": "Cartographier les actifs et flux de données IA",
  "Map the assets, datasets and interconnections supporting the AI systems in scope.": "Cartographier les actifs, jeux de données et interconnexions qui soutiennent les systèmes IA concernés.",
  "ISO/IEC 42001 AI Management System": "Système de management de l'IA ISO/IEC 42001",
  "Run the AIMS clauses & Annex A controls (scope, leadership, AI risk & impact assessment, controls, evidence) — start the dedicated ISO 42001 journey too.": "Dérouler les clauses du SMIA et les mesures de l'Annexe A (périmètre, leadership, appréciation du risque et d'impact IA, mesures, preuves) — lancez aussi le parcours ISO 42001 dédié.",
  "CSA AI Controls Matrix (AICM)": "Matrice de contrôles IA de la CSA (AICM)",
  "Implement and track the 247 AICM controls (18 domains) — imported as a framework with built-in mappings to ISO 42001, the EU AI Act and BSI AI C4.": "Mettre en œuvre et suivre les 247 contrôles AICM (18 domaines) — importés comme référentiel avec des correspondances intégrées vers ISO 42001, le règlement IA de l'UE et BSI AI C4.",
  "Run the AI impact assessment on individuals and society (and a DPIA where personal data is processed).": "Réaliser l'évaluation d'impact de l'IA sur les personnes et la société (et une AIPD lorsque des données personnelles sont traitées).",
  "Send the AICM AI-CAIQ questionnaire": "Envoyer le questionnaire AI-CAIQ de l'AICM",
  "Assess AI vendors and model providers with the CSA AI-CAIQ (320 questions, imported) as a TPRM questionnaire.": "Évaluer les fournisseurs IA et de modèles avec le CSA AI-CAIQ (320 questions, importé) comme questionnaire TPRM.",
  "Score & track vendor AI risk": "Noter et suivre le risque IA des fournisseurs",
  "Collect responses, score third-party AI risk, and set vendor criticality and due dates.": "Recueillir les réponses, noter le risque IA tiers, et fixer la criticité des fournisseurs et les échéances.",
  "Supply-chain & model provenance": "Chaîne d'approvisionnement et provenance des modèles",
  "Track the AI / software supply chain and model provenance (SBOM, components).": "Suivre la chaîne d'approvisionnement IA / logicielle et la provenance des modèles (SBOM, composants).",
  "Deploy AI guardrails": "Déployer les garde-fous IA",
  "Stand up the AI guardrails (prompt-injection, data-leak, jailbreak, tool-abuse) and review guardrail coverage & violations.": "Mettre en place les garde-fous IA (injection de prompt, fuite de données, jailbreak, abus d'outils) et examiner la couverture et les violations des garde-fous.",
  "Task the XOR agent": "Mandater l'agent XOR",
  "Use the XOR endpoint agent to discover AI usage on hosts and run AI-guardrail / log-hunt scans — 100% local.": "Utiliser l'agent de poste XOR pour découvrir l'usage de l'IA sur les hôtes et lancer des analyses garde-fous IA / chasse dans les logs — 100 % local.",
  "Monitor AI assets": "Surveiller les actifs IA",
  "Continuously monitor the availability, health and drift of AI endpoints and services.": "Surveiller en continu la disponibilité, la santé et la dérive des points d'accès et services IA.",
  "Detect & respond to AI incidents": "Détecter et répondre aux incidents IA",
  "Operate detection and incident response for AI-specific events (misuse, model compromise, data exposure).": "Exploiter la détection et la réponse aux incidents pour les événements propres à l'IA (usage abusif, compromission de modèle, exposition de données).",
  "AI usage awareness & training": "Sensibilisation et formation à l'usage de l'IA",
  "Roll out AI acceptable-use awareness and role-based training.": "Déployer la sensibilisation à l'usage acceptable de l'IA et une formation selon les rôles.",
  "Evidence & continuous assurance": "Preuves et assurance continue",
  "Gather evidence per control and prove the AI controls continuously from live telemetry.": "Rassembler les preuves par mesure et prouver les contrôles IA en continu à partir de la télémétrie en temps réel.",
  "Publish the AI trust posture": "Publier la posture de confiance IA",
  "Share your AI governance & security posture via the Trust Center.": "Partager votre posture de gouvernance et de sécurité IA via le Trust Center.",
  "Review & improve": "Revoir et améliorer",
  "Review the AIMS, AICM coverage, incidents and metrics; drive corrective actions and re-assess.": "Revoir le SMIA, la couverture AICM, les incidents et les indicateurs ; piloter les actions correctives et réévaluer.",
  // ── NIST AI RMF 1.0 ──
  "The NIST AI Risk Management Framework — a voluntary framework to govern, map, measure and manage the risks of AI systems and build trustworthy AI. Its four functions (GOVERN, MAP, MEASURE, MANAGE) and 72 subcategories are imported as a control catalogue (import_nist_ai_rmf.py); this journey walks them function by function.": "Le cadre de gestion des risques de l'IA du NIST — un cadre volontaire pour gouverner, cartographier, mesurer et gérer les risques des systèmes d'IA et bâtir une IA digne de confiance. Ses quatre fonctions (GOVERN, MAP, MEASURE, MANAGE) et 72 sous-catégories sont importées comme catalogue de contrôles (import_nist_ai_rmf.py) ; ce parcours les déroule fonction par fonction.",
  "GOVERN — culture & accountability": "GOVERN — culture & responsabilité",
  "Stand up AI governance & policy": "Mettre en place gouvernance & politiques IA",
  "Put AI risk policies, roles, accountability and training in place; integrate the trustworthy-AI characteristics into how you work (GOVERN 1–4).": "Mettre en place politiques, rôles, responsabilités et formation sur le risque IA ; intégrer les caractéristiques de l'IA digne de confiance dans vos pratiques (GOVERN 1–4).",
  "Establish and resource a mechanism to inventory AI systems and manage their lifecycle, incl. safe decommissioning (GOVERN 1.6/1.7).": "Établir et doter un mécanisme d'inventaire des systèmes d'IA et gérer leur cycle de vie, y compris une mise hors service sûre (GOVERN 1.6/1.7).",
  "Engagement & third-party AI": "Engagement & IA tierce",
  "Set processes for feedback from external AI actors and to manage third-party software/data supply-chain AI risk (GOVERN 5–6).": "Mettre en place des processus de retour des acteurs IA externes et de gestion du risque IA lié à la chaîne d'approvisionnement (logiciels/données tiers) (GOVERN 5–6).",
  "MAP — context & risk identification": "MAP — contexte & identification des risques",
  "Establish context": "Établir le contexte",
  "Document intended purpose, users, laws/norms, mission, business value and risk tolerances for each AI system (MAP 1).": "Documenter la finalité visée, les utilisateurs, les lois/normes, la mission, la valeur métier et les tolérances au risque pour chaque système d'IA (MAP 1).",
  "Categorize the AI system": "Catégoriser le système d'IA",
  "Define the task/method, knowledge limits, human oversight and TEVV considerations (MAP 2–3).": "Définir la tâche/méthode, les limites de connaissance, la supervision humaine et les considérations TEVV (MAP 2–3).",
  "Map risks, benefits & impacts": "Cartographier risques, bénéfices & impacts",
  "Map component and third-party risks, and characterize impacts to individuals, groups and society (MAP 4–5).": "Cartographier les risques des composants et des tiers, et caractériser les impacts sur les individus, les groupes et la société (MAP 4–5).",
  "MEASURE — assess & track": "MEASURE — évaluer & suivre",
  "Select methods & metrics": "Choisir méthodes & métriques",
  "Choose measurement approaches/metrics for the most significant AI risks; involve independent assessors (MEASURE 1).": "Choisir les approches/métriques de mesure pour les risques IA les plus importants ; impliquer des évaluateurs indépendants (MEASURE 1).",
  "Evaluate trustworthy characteristics": "Évaluer les caractéristiques de confiance",
  "Test for validity, safety, security/resilience, transparency, explainability, privacy, fairness/bias and environmental impact (MEASURE 2).": "Tester la validité, la sûreté, la sécurité/résilience, la transparence, l'explicabilité, la confidentialité, l'équité/les biais et l'impact environnemental (MEASURE 2).",
  "Track risks & gather feedback": "Suivre les risques & recueillir les retours",
  "Track existing/emergent AI risks over time and gather feedback on measurement efficacy (MEASURE 3–4).": "Suivre les risques IA existants/émergents dans le temps et recueillir des retours sur l'efficacité de la mesure (MEASURE 3–4).",
  "MANAGE — prioritize & act": "MANAGE — prioriser & agir",
  "Prioritize & respond to risks": "Prioriser & répondre aux risques",
  "Decide go/no-go, prioritize treatment, plan responses (mitigate/transfer/avoid/accept) and document residual risk (MANAGE 1).": "Décider go/no-go, prioriser le traitement, planifier les réponses (atténuer/transférer/éviter/accepter) et documenter le risque résiduel (MANAGE 1).",
  "Plan benefits & deactivation": "Planifier bénéfices & désactivation",
  "Maximize benefits, sustain value, recover from unknown risks, and be able to deactivate misbehaving AI (MANAGE 2).": "Maximiser les bénéfices, pérenniser la valeur, se remettre d'un risque inconnu, et pouvoir désactiver une IA déviante (MANAGE 2).",
  "Manage third-party & monitor post-deployment": "Gérer les tiers & surveiller après déploiement",
  "Monitor third-party resources and pre-trained models; run post-deployment monitoring, incident response and continual improvement (MANAGE 3–4).": "Surveiller les ressources tierces et les modèles pré-entraînés ; assurer la surveillance après déploiement, la réponse aux incidents et l'amélioration continue (MANAGE 3–4).",
};
