/**
 * purple-team.ts — Detection-coverage view (/purple-team?run=<id>).
 * Shows the ATT&CK detection coverage of an attack-chain run against the Sigma
 * library (gaps first), and generates a Sigma rule for any gap. English-only viewer.
 */
function $(id: string): HTMLElement { return document.getElementById(id)!; }
function esc(s: unknown): string { return String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!)); }

interface Tech { id: string; name: string; connectors: string[]; rules: number; sampleRules: string[]; covered: boolean }
interface Coverage { run: { ChainRunID: number; PlaybookName: string; SeedTarget: string } | null; techniques: Tech[]; stats: { total: number; covered: number; gaps: number; coveragePct: number }; }

const params = new URLSearchParams(location.search);
const runId = Number(params.get("run"));
const engagementId = Number(params.get("engagement"));
function attackUrl(id: string): string { return `https://attack.mitre.org/techniques/${id.replace(".", "/")}/`; }
function pctColor(p: number): string { return p >= 70 ? "#22c55e" : p >= 40 ? "#f59e0b" : "#ef4444"; }

function row(t: Tech): string {
  const status = t.covered
    ? `<span class="ok">✓ ${t.rules} Sigma rule${t.rules > 1 ? "s" : ""}</span>${t.sampleRules.length ? `<div class="rules">${t.sampleRules.map(esc).join(" · ")}</div>` : ""}`
    : `<span class="gap">✗ detection gap</span> <button class="btn btn-ghost btn-sm genbtn" data-id="${esc(t.id)}" data-name="${esc(t.name)}">⚙ Generate Sigma</button><pre class="sigma" id="sig-${esc(t.id)}" style="display:none"></pre>`;
  return `<tr>
    <td class="tid"><a href="${attackUrl(t.id)}" target="_blank" rel="noopener noreferrer">${esc(t.id)}</a></td>
    <td>${esc(t.name)}</td>
    <td>${t.connectors.map((c) => `<span class="tool">${esc(c)}</span>`).join("")}</td>
    <td>${status}</td>
  </tr>`;
}

async function genSigma(btn: HTMLButtonElement): Promise<void> {
  const id = btn.dataset.id!, name = btn.dataset.name!;
  const pre = $(`sig-${id}`); btn.disabled = true; pre.style.display = "block"; pre.textContent = "Generating…";
  try {
    const r = await fetch("/api/purple/sigma-suggest", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ techId: id, techName: name }) });
    const d = await r.json(); if (!r.ok) throw new Error(d.error || `HTTP ${r.status}`);
    pre.textContent = (d.offline ? "# starter skeleton (local AI offline) — tune to your environment\n" : `# generated by ${d.model}\n`) + d.yaml;
  } catch (e) { pre.textContent = `⚠️ ${e}`; }
  finally { btn.disabled = false; }
}

async function load(): Promise<void> {
  if (Number.isFinite(engagementId) && engagementId > 0) ($("pt-back") as HTMLAnchorElement).href = `/pentest?id=${engagementId}`;
  let d: Coverage;
  try { const r = await fetch(`/api/purple/chain/${runId}`); if (!r.ok) throw new Error(`HTTP ${r.status}`); d = await r.json(); }
  catch (e) { $("pt-results").innerHTML = `<div class="pt-empty">⚠️ ${esc(e)}</div>`; return; }
  if (d.run) $("pt-run").innerHTML = `Attack chain <b>${esc(d.run.PlaybookName)}</b> on <code>${esc(d.run.SeedTarget)}</code> — each tool mapped to ATT&CK, checked against your Sigma library.`;
  if (!d.techniques.length) { $("pt-results").innerHTML = `<div class="pt-empty">No mapped techniques for this run's tools.</div>`; return; }
  const st = d.stats;
  $("pt-gauge").style.display = "flex";
  $("pt-pct").textContent = `${st.coveragePct}%`; ($("pt-pct") as HTMLElement).style.color = pctColor(st.coveragePct);
  ($("pt-bar") as HTMLElement).style.width = `${st.coveragePct}%`; ($("pt-bar") as HTMLElement).style.background = pctColor(st.coveragePct);
  $("pt-gmeta").textContent = `${st.covered} of ${st.total} techniques have a detection · ${st.gaps} gap${st.gaps !== 1 ? "s" : ""}`;
  $("pt-results").innerHTML = `<table class="pt"><thead><tr><th>ATT&CK</th><th>Technique</th><th>Exercised by</th><th>Detection</th></tr></thead><tbody>${d.techniques.map(row).join("")}</tbody></table>`;
  $("pt-results").querySelectorAll("button.genbtn").forEach((b) => b.addEventListener("click", () => void genSigma(b as HTMLButtonElement)));
}

document.addEventListener("DOMContentLoaded", () => { if (!Number.isFinite(runId) || runId <= 0) { $("pt-results").innerHTML = `<div class="pt-empty">Open this from a chain run (no run id).</div>`; return; } void load(); });
