#!/usr/bin/env python3
"""gen_index.py — generate the connector catalogue index + a GitHub-browsable catalogue.

The connectors/ directory holds 1200+ connector sub-directories (one per connector). Reading all
of their connector.json manifests on every /connectors request costs ~270 ms (worse on OneDrive);
GitHub's web UI also truncates a directory listing at 1000 entries, so the flat layout is neither
fast to load nor browsable on GitHub. Rather than physically move 1200+ directories into category
sub-folders (which would break every path that resolves connectors/<id>/ in the Python runner, the
TypeScript route and the PHP marketplace), we keep the flat layout and generate two artefacts:

  * connectors/_index.json — ALL manifests aggregated into ONE file. Consumers read it in ~40 ms
    (a ~6x speed-up) instead of stat+parsing 1200+ files. Pure fast-path: stale/missing index just
    falls back to the live directory scan.
  * connectors/CATALOG.md  — every connector grouped by category, with a category table-of-contents
    and links to each connector's directory + README. This is the browse-by-category index for
    GitHub (each category section is well under the 1000-entry cap).

Run after adding/removing/editing connectors:  python connectors/gen_index.py
Idempotent; ASCII-only output; stdlib only.
"""
from __future__ import annotations

import json
import os
import glob
from collections import defaultdict
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))


def _slug(cat: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in (cat or "").lower()).strip("-") or "uncategorized"


def load_manifests() -> list[dict]:
    out = []
    for cj in sorted(glob.glob(os.path.join(HERE, "*", "connector.json"))):
        cid = os.path.basename(os.path.dirname(cj))
        try:
            with open(cj, "r", encoding="utf-8") as fh:
                m = json.load(fh)
        except Exception:  # noqa: BLE001 — skip a broken manifest, don't fail the whole index
            continue
        m.setdefault("id", cid)
        m["_dir"] = cid  # directory name (== id by convention) for path resolution
        out.append(m)
    return out


def write_index(mans: list[dict]) -> str:
    path = os.path.join(HERE, "_index.json")
    payload = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "count": len(mans),
        "connectors": mans,
    }
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
    return path


def _short(desc: str) -> str:
    d = (desc or "").replace("\n", " ").replace("|", "/").strip()
    # drop the [SCAFFOLD ...] tail so the catalogue reads cleanly
    i = d.find("[SCAFFOLD")
    if i >= 0:
        d = d[:i].strip()
    return (d[:160] + "...") if len(d) > 160 else d


def write_catalog(mans: list[dict]) -> str:
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for m in mans:
        by_cat[m.get("category") or "Uncategorized"].append(m)
    cats = sorted(by_cat, key=lambda c: (-len(by_cat[c]), c.lower()))

    lines: list[str] = []
    lines.append("# XORCISM Connector Catalogue")
    lines.append("")
    lines.append(f"**{len(mans)} connectors** across **{len(cats)} categories**. "
                 "Each connector is a sub-directory (`connectors/<id>/`) with a `connector.json` manifest, "
                 "a `run.py` and a `README.md`. This file is generated by `connectors/gen_index.py` — "
                 "browse by category below.")
    lines.append("")
    lines.append("> Loaders read the aggregated [`_index.json`](_index.json) (1 file) instead of "
                 "scanning every manifest; this catalogue is the human/GitHub-browsable view.")
    lines.append("")
    lines.append("## Categories")
    lines.append("")
    lines.append(" · ".join(f"[{c}](#{_slug(c)}) ({len(by_cat[c])})" for c in cats))
    lines.append("")
    for c in cats:
        items = sorted(by_cat[c], key=lambda m: str(m.get("id", "")).lower())
        lines.append(f"## {c}")
        lines.append("")
        lines.append(f"_{len(items)} connector(s)_")
        lines.append("")
        lines.append("| Connector | Type | Description |")
        lines.append("|---|---|---|")
        for m in items:
            cid = m.get("id", m.get("_dir", "?"))
            typ = m.get("type", "import")
            lines.append(f"| [`{cid}`]({cid}/) | {typ} | {_short(m.get('description', ''))} |")
        lines.append("")
    path = os.path.join(HERE, "CATALOG.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return path


def main() -> None:
    mans = load_manifests()
    # Write CATALOG.md FIRST, then _index.json LAST: on first generation both new files bump the
    # connectors/ dir mtime, so _index.json must be the newest file for the route's freshness check
    # (index.mtime >= dir.mtime) to trust it immediately.
    cat = write_catalog(mans)
    idx = write_index(mans)
    cats = len({m.get("category") or "Uncategorized" for m in mans})
    # ASCII-only prints (harness-safe)
    print(f"[gen_index] {len(mans)} connectors / {cats} categories")
    print(f"[gen_index] wrote {os.path.relpath(idx, HERE)} ({os.path.getsize(idx)//1024} KB)")
    print(f"[gen_index] wrote {os.path.relpath(cat, HERE)} ({os.path.getsize(cat)//1024} KB)")


if __name__ == "__main__":
    main()
